### ISSUE TITLE
Coverage crashes when code uses \ to allow newline in strings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#107]
```
What steps will reproduce the problem?
1. Have a code file with the following:
var foo = "hello\
 world";

2. Run coverage so this file is included
3. Watch it crash

What is the expected output? What do you see instead?
Expected is that coverage parses it correctly, as the backslash syntax is 
valid JS syntax.

Currently coverage fails with following:
INFO: Generating coverage for c:/foo/foo.js
Mar 17, 2010 10:47:02 AM 
com.google.jstestdriver.coverage.CoverageInstrumentingProcessor process
INFO: Generating coverage for c:/foo/FooTest.js
line 137:24 no viable alternative at character '\r'
line 138:17 mismatched character '\r' expecting '"'
..........E..
Total 13 tests (Passed: 12; Fails: 0; Errors: 1) (5.00 ms)
  Safari 531.21.10 Windows: Run 13 tests (Passed: 12; Fails: 0; Errors 1) 
(5.00 ms)
    FooTest.testFoo error (0.00 ms): Can't find variable: world
null
com.google.jstestdriver.FailureException
        at com.google.jstestdriver.FailureCheckerAction.run(Unknown Source)
        at com.google.jstestdriver.ActionRunner.runActions(Unknown Source)
        at com.google.jstestdriver.JsTestDriverServer.main(Unknown Source)


(.js filenames changed)

What version of the product are you using? On what operating system?

JsTestDriver 1.2.1, Coverage plugin 1.2.1
Windows XP
Safari 4

Please provide any additional information below.

Running JsTestDriver itself will accept this syntax and the test will pass.
```

Original issue reported on code.google.com by `jani.hartikainen` on 17 Mar 2010 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
I came across this one too - we escape newlines in this way when we have HTML 
strings in our code, it is more elegant than using concatenations just to keep 
the line length in check.  This bug means we can't use the coverage plugin :(

A couple of other things the coverage parser complains about (but do not cause 
crashes like above):
1. var foo = new function(){};  //or var foo = new function(){}();
2. debugger;


```

Original comment by `maly...@gmail.com` on 5 Mar 2011 at 7:43
