### ISSUE TITLE
jsTestDriver plugin for IntelliJIDEA seems compatible with other IntelliJ products (RubyMine, WebStorm), but is not.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#115]
```
What steps will reproduce the problem?
1. Download WebStorm 95.17
2. Install JsTestDriver plugin
3. On startup plugin will fail with NoClassDefFoundError: 
com/intellij/peer/PeerFactory 

What is the expected output? What do you see instead?

com/intellij/peer/PeerFactory: com/intellij/peer/PeerFactory
java.lang.NoClassDefFoundError: com/intellij/peer/PeerFactory
at com.google.jstestdriver.idea.JSTestDriverToolWindow.initToolWindow(Unknown 
Source)
at com.google.jstestdriver.idea.JSTestDriverToolWindow.projectOpened(Unknown 
Source)
at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:310)
at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:66)
at 
com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOp
ened(Project
Impl.java:345)
at 
com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(ProjectMana
gerImpl.jav
a:137)
at 
com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:9
25)
at 
com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerI
mpl.java:36
8)
at 
com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProject
OpenProces
sor.java:106)
at 
com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryPro
jectsManag
er.java:60)
at 
com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(Re
centProject
sManagerBase.java:242)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at 
com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageB
usConne
ctionImpl.java:101)
at 
com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.jav
a:183)
at 
com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:
175)
at 
com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:1
67)
at 
com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:40
)
at 
com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:106)
at $Proxy32.appStarting(Unknown Source)
at com.intellij.idea.IdeaApplication.b(IdeaApplication.java:238)
at com.intellij.idea.IdeaApplication.access$400(IdeaApplication.java:52)
at com.intellij.idea.IdeaApplication$IdeStarter$3.run(IdeaApplication.java:218)
at 
com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocat
or.java:319)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:610)
at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:500)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:368)
at 
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296
)
at 
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
at 
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201
)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.peer.PeerFactory
at 
com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:7
0)
at java.lang.ClassLoader.loadClass(ClassLoader.java:250)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:398)
... 37 more

What version of the product are you using? On what operating system?
version 1.2, Mac OSX Snow Leopard

Please provide any additional information below.
See also Jetbrains discussion on 
http://www.jetbrains.net/devnet/thread/287735?tstart=0
```

Original issue reported on code.google.com by `hts%link...@gtempaccount.com` on 6 Apr 2010 at 10:10

**Comment by GoogleCodeExporter** [comment]
```
Would be nice for this. Just today I ran into issues with checkbox event 
handling in
IE and not in Firefox.
```

Original comment by `gutzof...@gmail.com` on 20 May 2010 at 7:10

**Comment by GoogleCodeExporter** [comment]
```
Fixed in commit 696.
http://code.google.com/p/js-test-driver/source/detail?r=696
```

Original comment by `aeagle22206` on 14 Sep 2010 at 10:49
- Changed state: **Fixed**
