### ISSUE TITLE
Failure of jsTestDriver every 2nd or 3rd Time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#131]
```
What steps will reproduce the problem?

1. Configure Hudson on Windows 2003 to run the following : 
java -jar library\JsTestDriver-1.2.2.jar --port 4224 --browser "C:\Program 
Files\Mozilla Firefox\firefox.exe" --tests all --testOutput .\coverage 
--runnerMode DEBUG 

Expected tests to pass. This happens successfully first 2 times the command is 
run. However, every 3rd time this build runs I get the following error in the 
console output:

"Test Errors:
    atFailures during test run.
    at com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:108)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
Caused by:
    atjava.lang.RuntimeException: Could not start browser CommandLineBrowserRunner [browserPath=C:\Program Files\Mozilla Firefox\firefox.exe, process=java.lang.ProcessImpl@309f9f, processFactory=com.google.jstestdriver.SimpleProcessFactory@3fa6cd] in 30

Test Errors:
    atFailures during test run.
    at com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:108)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
Caused by:
java.lang.RuntimeException: Could not start browser CommandLineBrowserRunner 
[browserPath=C:\Program Files\Mozilla Firefox\firefox.exe, 
process=java.lang.ProcessImpl@309f9f, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@3fa6cd] in 
30Unexpected Runner Condition: Failures during test run."


I am running version 1.2.22 of js-test-driver 
with Hudson CI - version 1.388 on Windows 2003 (with latest service packs) and 
Firefox 3.6.6 and Java version 1.6.0_21
```

Original issue reported on code.google.com by `debounc...@gmail.com` on 12 Aug 2010 at 12:36

**Comment by GoogleCodeExporter** [comment]
```
Sounds like the same issue we get (running on Windows 2003). In our case, the 
server and client both appear to be running, but the server does not detect the 
client and so it times out after 30 seconds of waiting.
```

Original comment by `willhol...@gmail.com` on 12 Aug 2010 at 11:53

**Comment by GoogleCodeExporter** [comment]
```
That looks entirely like an issue with the windows box. The complaint is that 
firefox doesn't call to the server within 30 seconds.

I'm dismissing this issue because we have a hudson build for JsTD that is doing 
just fine. If you can determine that there is an issue with *how* the browser 
is started, or is the browser displays an error after opening, feel free to 
reopen the issue.
```

Original comment by `corbinrs...@gmail.com` on 12 Aug 2010 at 2:09
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
I'm trying to gather more information on our issue. I have attached the tail 
end of the log when it fails. Can you give me any direction as to how I could 
investigate this further?
```

Original comment by `willhol...@gmail.com` on 13 Aug 2010 at 8:43

Attachments:
- [jstestdriver-fail.txt](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-131/comment-3/jstestdriver-fail.txt)

**Comment by GoogleCodeExporter** [comment]
```
We are experiencing this issue as well. About 1 in 10 builds fail with the 
following exception from JsTestDriver: 

java.lang.RuntimeException: Could not start browser CommandLineBrowserRunner 
[browserPath=c:\Program Files (x86)\Mozilla Firefox\firefox.exe, 
process=java.lang.ProcessImpl@132ae7, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@65b738] in 30

When it fails we force another build, and that one usually goes through, but 
the team is understandably annoyed with the problem. 

We are running 64-bit Windows 2008 Server with 32-bit CruiseControl.NET. Please 
let us know if there is more information that we can provide (logs, machine 
info, etc) to facilitate the investigation of this issue. We consider this to 
be an intermittent defect in JsTestDriver, since JsTestDriver fails to reliably 
manage its required resources (Firefox, in this case) under our server 
configuration. 

Thanks for re-opening this issue and allocating some bandwidth to investigating 
it. 
```

Original comment by `marclitc...@gmail.com` on 4 Jan 2011 at 10:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 4 Jan 2011 at 10:22
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
The next version (or head for the adventurous) will have retries.

We solved this issue on the jstd cbuild by allocating more ram and processor to 
it. I really wish I had more insight into why a resource constrained 
environment makes the browsers so flaky.
```

Original comment by `corbinrs...@gmail.com` on 10 Feb 2011 at 1:57
