### ISSUE TITLE
Unhandled event loop exception caused by NPE when running JsTestDriver test on eclipse

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#136]
```
What steps will reproduce the problem?
1. Installed the plugin, restarted eclipse.  (version details below)
2. Server starts okay and firefox connects fine.
3. Right click on a test and run as a JsTestDriver Test.

What is the expected output? What do you see instead?

It should work... however the following exception appears in the error log:

org.eclipse.swt.SWTException: Failed to execute runnable 
(java.lang.NullPointerException)
at org.eclipse.swt.SWT.error(SWT.java:4083)
at org.eclipse.swt.SWT.error(SWT.java:3998)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:137)
at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3527)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3174)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
at org.eclipse.jface.window.Window.open(Window.java:801)
at 
org.eclipse.ui.internal.views.log.EventDetailsDialog.open(EventDetailsDialog.jav
a:176)
at 
org.eclipse.ui.internal.views.log.EventDetailsDialogAction.run(EventDetailsDialo
gAction.java:98)
at org.eclipse.ui.internal.views.log.LogView$15.doubleClick(LogView.java:536)
at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:824)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
at 
org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java
:822)
at 
org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeView
er.java:1421)
at 
org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredVie
wer.java:1225)
at 
org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:
238)
at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:235)
at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:296)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3552)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3171)
at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2629)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2593)
at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2427)
at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:670)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:663)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at 
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java
:115)
at 
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at 
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ecli
pseAppLauncher.java:110)
at 
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLau
ncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
Caused by: java.lang.NullPointerException
at 
com.google.eclipse.javascript.jstestdriver.ui.runner.ActionRunnerFactory.getActi
onBuilder(ActionRunnerFactory.java:154)
at 
com.google.eclipse.javascript.jstestdriver.ui.runner.ActionRunnerFactory.getDryA
ctionRunner(ActionRunnerFactory.java:79)
at 
com.google.eclipse.javascript.jstestdriver.ui.launch.JsTestDriverLaunchShortcut$
1.run(JsTestDriverLaunchShortcut.java:228)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
... 42 more



What version of the product are you using? On what operating system?

eclipse.buildId=I20100608-0911
java.version=1.6.0_18
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_AU
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product 
org.eclipse.epp.package.jee.product



Please provide any additional information below.

```

Original issue reported on code.google.com by `joel_rob...@fastmail.fm` on 20 Sep 2010 at 12:20

**Comment by GoogleCodeExporter** [comment]
```
Is there any workarounds to fix this issue?
```

Original comment by `Hazem.sa...@gmail.com` on 1 Aug 2011 at 1:43
