### ISSUE TITLE
Compatibility with prototype javascript lib

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#14]
```
What steps will reproduce the problem?
1. Load in load jsTestDriver.conf the prototype lib:
 - Prototype/*.js
2. Execute test as described in documentation

What is the expected output? Testreport with more than 0 tests.

What do you see instead? Total 0 tests (Passed: 0; Fails: 0; Errors: 0)
(0,00 ms)

What version of the product are you using? On what operating system?
JsTestDriver-1.0b.jar

Please provide any additional information below.
I know the problem with jquery and this: jQuery.noConflict(); solution.

I like this js-test solution very much. But i have to use prototype in my
applications.

Thanks for the work!
```

Original issue reported on code.google.com by `ralf.puc...@googlemail.com` on 30 Jun 2009 at 9:12

**Comment by GoogleCodeExporter** [comment]
```
Hi Ralf,

I'm going to send a change pretty soon that will just do that. Just sent an 
email on 
our mailing list to let people know so if they were relying on it they can 
change 
their code so it doesn't break.
```

Original comment by `toc...@gmail.com` on 30 Jun 2009 at 8:41
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Ok it was submitted. Let me know if it fixes your problem.
```

Original comment by `toc...@gmail.com` on 30 Jun 2009 at 9:03
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi tocman,

Thank you for the fast response.

I checked out (revision 98) and i tried out. I seems that it works but there is
another issue:

This is error message in the firefox (firebug plugin) when i include the 
prototype.js:
8< --
Error 500 The JsonDeserializer
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter@da6bf4
 failed to deserialized json object "[{"fileSrc":
"/test//home/rpu/workspace/GeowayJS/Geoway/Prototype
/prototype-1.6.0.3.js", "timestamp": 1246349643000}, {"fileSrc":
"/test//home/rpu/workspace/GeowayJS
/Geoway/Geoway.js", "timestamp": 1246373471000}, {"fileSrc":
"/test//home/rpu/workspace/GeowayJS/test
/GeowayTests.js", "timestamp": 1246350554000}]" given the type
com.google.gson.ParameterizedTypeImpl
@c98394
8< ---

And the jsTestDriver Server throws this message:

8< ---
01.07.2009 10:25:11 org.slf4j.impl.JCLLoggerAdapter error
SCHWERWIEGEND: /query/1
com.google.gson.JsonParseException: The JsonDeserializer
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter@da6bf4 failed to
deserialized json object "[{"fileSrc":
"/test//home/rpu/workspace/GeowayJS/Geoway/Prototype/prototype-1.6.0.3.js",
"timestamp": 1246349643000}, {"fileSrc":
"/test//home/rpu/workspace/GeowayJS/Geoway/Geoway.js", "timestamp": 
1246373471000},
{"fileSrc": "/test//home/rpu/workspace/GeowayJS/test/GeowayTests.js", 
"timestamp":
1246350554000}]" given the type com.google.gson.ParameterizedTypeImpl@c98394
    at
com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExc
eptionWrapper.java:63)
    at
com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(Js
onObjectDeserializationVisitor.java:106)
    at com.google.gson.ObjectNavigator.navigateClassFields(ObjectNavigator.java:135)
    at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:116)
    at
com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializa
tionContextDefault.java:75)
    at
com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializatio
nContextDefault.java:49)
    at com.google.gson.Gson.fromJson(Gson.java:373)
    at com.google.gson.Gson.fromJson(Gson.java:321)
    at com.google.gson.Gson.fromJson(Gson.java:297)
    at com.google.jstestdriver.BrowserQueryResponseServlet.service(Unknown Source)
    at com.google.jstestdriver.BrowserQueryResponseServlet.doPost(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:363)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:879)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:741)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:213)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:403)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:522)
Caused by: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot 
be cast
to com.google.gson.JsonArray
    at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:91)
    at
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTyp
eAdapters.java:399)
    at
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTyp
eAdapters.java:369)
    at
com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExc
eptionWrapper.java:50)
    ... 23 more

8< ---

Thanks for your effort.

Best regards
Ralf



```

Original comment by `ralf.puc...@googlemail.com` on 1 Jul 2009 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
Hi Ralf,

Indeed prototype seems to make JsTestDriver unhappy. I'm suspecting they are
redefining something we are using. I'll investigate this soon.
```

Original comment by `toc...@gmail.com` on 1 Jul 2009 at 4:52

**Comment by GoogleCodeExporter** [comment]
```
Hey Ralf,

I've just submitted a change that should really fix the issue, can you sync to 
HEAD 
and check if it works as it should for you now?

Thanks !
```

Original comment by `toc...@gmail.com` on 7 Jul 2009 at 12:13

**Comment by GoogleCodeExporter** [comment]
```
hi tocman,

You are right. It works. And i use also scriptaculous, OpenLayers.
My tests running now also under continous testing environment. Very nice. 
Good work!
```

Original comment by `ralf.puc...@googlemail.com` on 7 Jul 2009 at 11:34

**Comment by GoogleCodeExporter** [comment]
```
Hi tocman,

We tried to update to rev 107 as well as to trunk HEAD (rev 142) and get the 
following error:

Jul 22, 2009 10:47:33 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Logging to org.slf4j.impl.JCLLoggerAdapter(org.mortbay.log) via 
org.mortbay.log.Slf4jLog
Jul 22, 2009 10:47:33 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: jetty-6.1.x
Jul 22, 2009 10:47:33 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Started SocketConnector@0.0.0.0:1234
Jul 22, 2009 10:47:39 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Browser Captured: Firefox version 3.5.1 (1)
Jul 22, 2009 10:47:44 AM org.slf4j.impl.JCLLoggerAdapter error
SEVERE: /query/1
com.google.gson.JsonParseException: The JsonDeserializer 
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter@2acc57 failed to 
deserialized
json object "[{"fileSrc": 
"/test/C:/dev/projects/mb/trunk/web/resource/communicator/communicator-
api/target/communicator-api-2.6-SNAPSHOT/prototype-1.6.0.3.js", "timestamp": 
1248284224967}]" given the type com.google.gson.ParameterizedTypeImpl@ca24a1
        at 
com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExc
eptio
nWrapper.java:63)
        at 
com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(Js
onObj
ectDeserializationVisitor.java:106)
        at 
com.google.gson.ObjectNavigator.navigateClassFields(ObjectNavigator.java:135)
        at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:116)
        at 
com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializa
tionC
ontextDefault.java:75)
        at 
com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializatio
nCont
extDefault.java:49)
        at com.google.gson.Gson.fromJson(Gson.java:373)
        at com.google.gson.Gson.fromJson(Gson.java:321)
        at com.google.gson.Gson.fromJson(Gson.java:297)
        at com.google.jstestdriver.BrowserQueryResponseServlet.service(Unknown 
Source)
        at com.google.jstestdriver.BrowserQueryResponseServlet.doPost(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:363)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:324)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
        at 
org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:879)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:741)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:213)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:403)
        at 
org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at 
org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:522)
Caused by: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot 
be cast 
to com.google.gson.JsonArray
        at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:91)
        at 
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTyp
eAdap
ters.java:399)
        at 
com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTyp
eAdap
ters.java:369)
        at 
com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExc
eptio
nWrapper.java:50)
        ... 23 more

It looks to be the same as Ralf's error.  We tried an older version of 
prototype as 
well. Any help would be appreciated.

Thanks.
```

Original comment by `yahui...@gmail.com` on 22 Jul 2009 at 5:56
