### ISSUE TITLE
Server won't start if using coverage plugin without setting --browser specifically

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#146]
```
What steps will reproduce the problem?
1. Add coverage plugin to your config:
plugin:
  - name: "coverage"
    jar: "target/bin/plugins/coverage.jar"

2. Try to start server
java -jar JsTestDriver-1.2.2.jar --port 4224

What is the expected output? What do you see instead?
Server should be started, but it doesn't. It seems that browsers have to be 
defined for whatever reason.

When using --runnerMode DEBUG it's shown to try to reset browsers:
8.10.2010 9:32:40 com.google.jstestdriver.ActionRunner runActions
INFO: Running com.google.jstestdriver.ServerStartupAction@2be2befa
8.10.2010 9:32:40 com.google.jstestdriver.ServerStartupAction run
INFO: Starting server...
8.10.2010 9:32:40 org.mortbay.log.Slf4jLog info
INFO: Transparent ProxyServlet @ forward to http://localhost:4224
8.10.2010 9:32:40 com.google.jstestdriver.JsTestDriverServer start
FINE: Starting the server.
8.10.2010 9:32:40 com.google.jstestdriver.ActionRunner runActions
INFO: Finished com.google.jstestdriver.ServerStartupAction@2be2befa
8.10.2010 9:32:40 com.google.jstestdriver.ActionRunner runActions
INFO: Running com.google.jstestdriver.BrowserActionsRunner@628f9a32
8.10.2010 9:32:40 com.google.jstestdriver.BrowserActionsRunner run
FINEST: Starting BrowserActions [com.google.jstestdriver.ResetAction@41d47b2b, 
com.google.jstestdriver.ResetAction@41d47b2b].
8.10.2010 9:32:40 com.google.jstestdriver.HttpServer fetch
FINEST: Fetching http://localhost:4224/cmd?listBrowsers
8.10.2010 9:32:40 com.google.jstestdriver.HttpServer fetch
FINEST: Fetch response []
8.10.2010 9:32:40 com.google.jstestdriver.JsTestDriver main
FINE: Error {}
java.lang.RuntimeException: No browsers available, yet actions requested. If 
running against a persistent server please capture browsers. Otherwise, e
nsure that browsers are defined.
        at com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:69)
        at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
        at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
java.lang.RuntimeException: No browsers available, yet actions requested. If 
running against a persistent server please capture browsers. Otherwise, e
nsure that browsers are defined.
        at com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:69)
        at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
        at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
Unexpected Runner Condition: No browsers available, yet actions requested. If 
running against a persistent server please capture browsers. Otherwise,
ensure that browsers are defined.
 Use --runnerMode DEBUG for more information.


What version of the product are you using? On what operating system?
1.2.2, Windows 7.
```

Original issue reported on code.google.com by `Jarmo.P@gmail.com` on 8 Oct 2010 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
I also see this on debian 3.1.
 uname -a
Linux devv1 2.6.18-14-fza-686-bigmem #1 SMP Thu Jan 1 17:20:47 UTC 2009 i686 
GNU/Linux
```

Original comment by `jacobodo...@gmail.com` on 18 Oct 2010 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
and my mac :10.6.4 :'(
```

Original comment by `jacobodo...@gmail.com` on 19 Oct 2010 at 3:34

**Comment by GoogleCodeExporter** [comment]
```
Fixed on head, revision 760.
```

Original comment by `corbinrs...@gmail.com` on 28 Oct 2010 at 12:32
- Changed state: **Fixed**
