### ISSUE TITLE
Could not start browser CommandLineBrowserRunner

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#158]
```
What steps will reproduce the problem?
1. Set up a teamcity ci server.
2. Write an ant build file to launch the tests.
3. Trigger the test on the teamcity server.

What is the expected output? What do you see instead?
The java script tests should be run like on the local development machine.

What version of the product are you using? On what operating system?
1.2.2 on Ubuntu 10.04

Please provide any additional information below.
My ant target looks like this:
<code>
  <target name="tests.javascript" depends="build.modules, build.all.artifacts">
    <property name="browsers" value="/usr/bin/firefox,/usr/bin/google-chrome"/>
    <java jar="/usr/local/share/jsTestDriver/JsTestDriver.jar" fork="true">
      <arg line="--port 9876"/>
      <arg line="--config ${basedir}/Client/jsTestDriver.conf"/>
      <arg line="--browser ${browsers}"/>
      <arg line="--tests all"/>
    </java>
  </target>
</code>

If I run it on my local test machine e.g. run ant task from idea it works like 
a charm. Although the firefox is not closed after the tests are run.
If the ant build is triggered on the server I get the following error messages:

[20:45:31]: [java] Unexpected Runner Condition: Failures during test run.
[20:45:31]: [java]  Use --runnerMode DEBUG for more information.
[20:45:31]: [java] Nov 2, 2010 8:45:31 PM 
com.google.jstestdriver.BrowserActionsRunner run
[20:45:31]: [java] FINE: Finished BrowserActions 
[com.google.jstestdriver.RunTestsAction@4aab7165].
[20:45:31]: [java] Nov 2, 2010 8:45:31 PM com.google.jstestdriver.JsTestDriver 
main
[20:45:31]: [java] FINE: Error {}
[20:45:31]: [java] Test Errors:
[20:45:31]: [java]  atFailures during test run.
[20:45:31]: [java]  at 
com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:108)
[20:45:31]: [java]  at 
com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
[20:45:31]: [java]  at 
com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
[20:45:31]: [java] Caused by:
[20:45:31]: [java]  atjava.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/google-chrome, 
process=java.lang.UNIXProcess@27958cc2, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@4b4c28db] in 30
[20:45:31]: [java] Caused by:
[20:45:31]: [java]  atjava.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@4ed9f47, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@c73f0d8] in 30
[20:45:31]: [java] Test Errors:
[20:45:31]: [java]  atFailures during test run.
[20:45:31]: [java]  at 
com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:108)
[20:45:31]: [java]  at 
com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
[20:45:31]: [java]  at 
com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
[20:45:31]: [java] Caused by:
[20:45:31]: [java] java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/google-chrome, 
process=java.lang.UNIXProcess@27958cc2, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@4b4c28db] in 
30java.lang.RuntimeException: Could not start browser CommandLineBrowserRunner 
[browserPath=/usr/bin/firefox, process=java.lang.UNIXProcess@4ed9f47, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@c73f0d8] in 30
[20:45:31]: [java] Java Result: 1
```

Original issue reported on code.google.com by `jens.jah...@gmail.com` on 2 Nov 2010 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
I was able to solve the issue by installing XVFB on the server and 
reconfiguring the ant build to:
  <target name="tests.javascript"
          depends="build.modules, build.all.artifacts">
    <property name="browsers"
              value="/usr/bin/firefox,/usr/bin/google-chrome"/>
    <exec executable="/usr/bin/xvfb-run">
      <arg line="java"/>
      <arg line="-jar /usr/local/share/jsTestDriver/JsTestDriver.jar"/>
      <arg line="--port 9876"/>
      <arg line="--config ${basedir}/Client/jsTestDriver.conf"/>
      <arg line="--browser ${browsers}"/>
      <arg line="--tests all"/>
    </exec>
  </target>

Now it works like a charme.
```

Original comment by `jens.jah...@gmail.com` on 3 Nov 2010 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same issue sometimes with Ubuntu 10.10 with Xvfb and Firefox 
3.6.12:

Dec 23, 2010 2:37:03 PM com.google.jstestdriver.HttpServer fetch
FINEST: Fetch response []
Dec 23, 2010 2:37:03 PM 
com.google.jstestdriver.browser.CommandLineBrowserRunner stopBrowser
WARNING: Unexpected shutdown java.lang.UNIXProcess@46e13e7b 1
Dec 23, 2010 2:37:03 PM 
com.google.jstestdriver.browser.BrowserActionExecutorAction run
FINE: Finished BrowserActions [com.google.jstestdriver.ResetAction@6571120a, 
com.google.jstestdriver.RunTestsAction@6257828d].
Dec 23, 2010 2:37:03 PM com.google.jstestdriver.ActionRunner runActions
INFO: Finished 
com.google.jstestdriver.browser.BrowserActionExecutorAction@295a4523
Dec 23, 2010 2:37:03 PM com.google.jstestdriver.ActionRunner runActions
INFO: 
Dec 23, 2010 2:37:03 PM com.google.jstestdriver.JsTestDriver main
FINE: Error {}
Failures during test run.
Caused by:
java.lang.RuntimeException: Failed after 1 tries.
Failure 1: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
    at com.google.jstestdriver.util.Retry.retry(Retry.java:70)
    at com.google.jstestdriver.browser.BrowserManagedRunner.call(BrowserManagedRunner.java:49)
    at com.google.jstestdriver.browser.BrowserManagedRunner.call(BrowserManagedRunner.java:22)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
    at com.google.jstestdriver.browser.BrowserManagedRunner.startBrowserAndWaitForResponse(BrowserManagedRunner.java:69)
    at com.google.jstestdriver.browser.BrowserManagedRunner.access$000(BrowserManagedRunner.java:22)
    at com.google.jstestdriver.browser.BrowserManagedRunner$1.run(BrowserManagedRunner.java:52)
    at com.google.jstestdriver.browser.BrowserManagedRunner$1.run(BrowserManagedRunner.java:50)
    at com.google.jstestdriver.util.Retry.retry(Retry.java:57)
    ... 12 more

    at com.google.jstestdriver.browser.BrowserActionExecutorAction.run(BrowserActionExecutorAction.java:141)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)

Caused by:java.lang.RuntimeException: Failed after 1 tries.
Failure 1: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
java.lang.RuntimeException: Failed after 1 tries.
Failure 1: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
    at com.google.jstestdriver.util.Retry.retry(Retry.java:70)
    at com.google.jstestdriver.browser.BrowserManagedRunner.call(BrowserManagedRunner.java:49)
    at com.google.jstestdriver.browser.BrowserManagedRunner.call(BrowserManagedRunner.java:22)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
    at com.google.jstestdriver.browser.BrowserManagedRunner.startBrowserAndWaitForResponse(BrowserManagedRunner.java:69)
    at com.google.jstestdriver.browser.BrowserManagedRunner.access$000(BrowserManagedRunner.java:22)
    at com.google.jstestdriver.browser.BrowserManagedRunner$1.run(BrowserManagedRunner.java:52)
    at com.google.jstestdriver.browser.BrowserManagedRunner$1.run(BrowserManagedRunner.java:50)
    at com.google.jstestdriver.util.Retry.retry(Retry.java:57)
    ... 12 more
Failures during test run.
Caused by:
java.lang.RuntimeException: Failed after 1 tries.
Failure 1: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
    at com.google.jstestdriver.util.Retry.retry(Retry.java:70)
    at com.google.jstestdriver.browser.BrowserManagedRunner.call(BrowserManagedRunner.java:49)
    at com.google.jstestdriver.browser.BrowserManagedRunner.call(BrowserManagedRunner.java:22)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
    at com.google.jstestdriver.browser.BrowserManagedRunner.startBrowserAndWaitForResponse(BrowserManagedRunner.java:69)
    at com.google.jstestdriver.browser.BrowserManagedRunner.access$000(BrowserManagedRunner.java:22)
    at com.google.jstestdriver.browser.BrowserManagedRunner$1.run(BrowserManagedRunner.java:52)
    at com.google.jstestdriver.browser.BrowserManagedRunner$1.run(BrowserManagedRunner.java:50)
    at com.google.jstestdriver.util.Retry.retry(Retry.java:57)
    ... 12 more

    at com.google.jstestdriver.browser.BrowserActionExecutorAction.run(BrowserActionExecutorAction.java:141)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
Caused by:
java.lang.RuntimeException: Failed after 1 tries.
Failure 1: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [browserPath=/usr/bin/firefox, 
process=java.lang.UNIXProcess@46e13e7b, 
processFactory=com.google.jstestdriver.SimpleProcessFactory@344e17f9] in 30
Unexpected Runner Condition: Failures during test run.

```

Original comment by `mikkonet...@gmail.com` on 23 Dec 2010 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same problem on Windows Server 2008 R2. Anyone have a 
fix/workaround?
```

Original comment by `herman...@gmail.com` on 22 Feb 2011 at 8:51

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem on Windows server 2003 SP2 with hudson as CI solution. 
and I tried both command line and ant. IE8 can work if I launch it before 
triggering the build. firefox or chrome failed. 
```

Original comment by `yangyu...@gmail.com` on 4 Mar 2011 at 9:51

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
These issues generally relate to the way the system is setup. Jstd merely 
starts the provided binary using a process runner. If there are issues in the 
environment that prevent starting the browser (not sent to the right virtual 
frame buffer, etc. etc.), or cause the browser to start in an awkward state 
(popups about restoring browser state, browser not navigating to the provided 
webaddress) there is little jstd can do.

I suggest, especially with the wide range of os/browser combinations, that you 
attempt to run this from the command line and observe the browser behaviour. 
You may need to provide a wrapper script to better define the environment for 
each browser.

That being said, I am looking into using Selenium as a browser provider. I have 
no interest in trying to re-invite a wheel that another project has managed to 
do so.
```

Original comment by `corbinrs...@gmail.com` on 5 Mar 2011 at 12:25

**Comment by GoogleCodeExporter** [comment]
```
I find the problem on my environment. I didn't change the default settings of 
tomcat service (for hudson), so the tomcat service was running with the 
'DefaultUser', different with current logged user. I think it results in the 
browser starting in an awkward state.

two choices here:

1, start tomcat from commandline
2, change to use your current credential to start tomcat service 
(service/properties/log on)
```

Original comment by `yangyu...@gmail.com` on 7 Mar 2011 at 2:28

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem when I update from v1.2.2 to v1.3.1. I'm using a custom 
little browser built in QT that works fine with v1.2.2. With the rest of the 
browsers works fine.
Anyone have a solution?
```

Original comment by `maldonadofacundo@gmail.com` on 9 Mar 2011 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
The messaging isn't great, but it means that the browser doesn't not get to 
state in which it contacts the server. Please debug the browser state locally, 
as there is only so much jstd can do from the command line.
```

Original comment by `corbinrs...@gmail.com` on 7 Jun 2012 at 9:19
