### ISSUE TITLE
Choose config file by browsing through my Project (EclipsePlugin)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#175]
```
At the moment, if I do a new run configuration in eclipse, I have a dropdown 
list for my project, which is fine and the same for the config file which 
isn't. It requires me to have my config file stored in the root-folder of my 
project. I'm quite unhappy with this solution as I would normally store 
everything test-relevant under my tests/ folder.

Instead of giving me a dropdown list for choosing the config file I wish to 
have some sort of a file-browser.

So, letting me place my config files where I want them and not where JSTD wants 
them.

Thanks very much.

```

Original issue reported on code.google.com by `unigossi` on 13 Dec 2010 at 11:11

**Comment by GoogleCodeExporter** [comment]
```
I tried to change it by myself based on r613 (for eclipse).

Things changed:

you can select configure file by a pop-up dialog. Pay attention to the path 
defined in the conf file, it should be relative to the conf file.

How to use:

after you install jsTestDriver plugin,

1, copy the attached two files:

com.google.eclipse.javascript.jstestdriver.core_1.1.1.e.jar
com.google.eclipse.javascript.jstestdriver.ui_1.1.1.e.jar

to your EclipseFolder\plugins, overwrite the existing ones (backup them if you 
need)

2, search jsTestDriver.jar in:

YOUR_ECLIPSE_FOLDER\configuration\org.eclipse.osgi\bundles

and copy attached jsTestDriver.jar to the folder you get above, overwrite the 
existing ones.
```

Original comment by `yangyu...@gmail.com` on 28 Mar 2011 at 3:34

Attachments:
- [JsTestDriver.jar](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-1/JsTestDriver.jar)
- [com.google.eclipse.javascript.jstestdriver.core_1.1.1.e.jar](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-1/com.google.eclipse.javascript.jstestdriver.core_1.1.1.e.jar)
- [com.google.eclipse.javascript.jstestdriver.ui_1.1.1.e.jar](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-1/com.google.eclipse.javascript.jstestdriver.ui_1.1.1.e.jar)

**Comment by GoogleCodeExporter** [comment]
```
the source code.

actually only eclipse plugin related files need be updated. but I found the 
modified plugin jars can't work together with the original jsTestDriver.jar 
file, so you need the attached jsTestDriver.jar file which is copied from 
plugins\com.google.eclipse.javascript.jstestdriver.core\lib
```

Original comment by `yangyu...@gmail.com` on 28 Mar 2011 at 3:50

Attachments:
- [JsTestDriverLaunchTab.java](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-2/JsTestDriverLaunchTab.java)

**Comment by GoogleCodeExporter** [comment]
```
Wonderful, would love to see this implemented :)

For me: I didn't need to update JsTestDriver.jar - never do I have one in the 
bundles-folder either.
```

Original comment by `unigossi` on 28 Mar 2011 at 7:39

**Comment by GoogleCodeExporter** [comment]
```
I hope this or at least the ability to specify config path gets added. I 
installed the jars provided above, and it works!. Then, I saw the path it was 
using and thought that if I just entered that myself with the stock plugin, it 
would work. But, it doesn't. So, I had to re-install the updated jars to be 
able to specify a config file in a non-root path.

Please update the the plugin to allow non-root config files. I'm afraid the 
plugin will update and my tests won't run.
```

Original comment by `cfchris` on 8 Feb 2012 at 8:41

**Comment by GoogleCodeExporter** [comment]
```
Currently, the plugin searches for all files ending with {.conf,.jstd} in the 
project. What version are you on?
```

Original comment by `corbinrs...@gmail.com` on 8 Feb 2012 at 8:47

**Comment by GoogleCodeExporter** [comment]
```
I am on version 1.1.1.e. Is there a newer version? I tried closing and opening 
the project, restarting Eclipse. Nothing seemed to get it to pickup conf files 
in anything but the root of the project.
```

Original comment by `cfchris` on 9 Feb 2012 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
there should, visible, 1.3.3.a.

I'm not sure I got the release right, though. If not, please let me
know and I'll take another crack at it.
```

Original comment by `corbinrs...@gmail.com` on 9 Feb 2012 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
Is there a new update URL to check for this new version, or is it still:

   http://js-test-driver.googlecode.com/svn/update/

If so, I can't see any new versions available yet.
```

Original comment by `dominic....@gmail.com` on 9 Feb 2012 at 6:51

**Comment by GoogleCodeExporter** [comment]
```
I don't see a new version of the plugin. Attached is what I see. It has the 
update URL and all the settings in the dialog. (Same note as issue 157. Sorry 
for the noise.)
```

Original comment by `cfchris` on 9 Feb 2012 at 4:51

Attachments:
- [Eclipse - JsTestDriver Update Site.jpg](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-9/Eclipse - JsTestDriver Update Site.jpg)

**Comment by GoogleCodeExporter** [comment]
```
corbin, let us know if you have any luck getting a new version out to the 
update site. I'm dying to see if a new version fixes any of the other issues I 
have with the plugin. (Mainly that it doesn't show any details when clicking on 
the test results.)
```

Original comment by `cfchris` on 10 Feb 2012 at 11:51

**Comment by GoogleCodeExporter** [comment]
```
Alright, I believe I got it right. It's worth noting that plugin head is here: 
http://code.google.com/p/js-test-driver/source/browse/trunk/eclipse-plugin/featu
res/com.google.eclipse.javascript.jstestdriver.updatesite/

For the adventurous, of course.
```

Original comment by `corbinrs...@gmail.com` on 14 Feb 2012 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
Cory,

First, thanks for pushing this tool forward. I can't wait to make it a part of 
my teams workflow.

OK, now the bad news. I ran the update. Now, I can't get to the "run 
configurations" screen. I just deleted my existing run configuration. And 
trying to add a new one errors too. They both end up in the below sequence of 
screens.

First, an error screen, then a prompt, then a blank config. (See attached 
screens.)

I tried running the global update on all of my plugins and doing a -clean 
restart of Eclipse before sending this.

Here is my setup:
Windows 7 Pro
Eclipse_3.7_JS_x64 () - Version: Indigo Service Release 1 - Build id: 
20110916-0149
Js Test Driver 1.3.4.a
```

Original comment by `cfchris` on 14 Feb 2012 at 7:10

Attachments:
- [Error.jpg](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-12/Error.jpg)
- [Prompt.jpg](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-12/Prompt.jpg)
- [BlankForm.jpg](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-175/comment-12/BlankForm.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Okay, I did a bad package. Try 1.3.4.b. I tried signing them, but I've 
obviously missed a step in the process of distributing self signed plugins.
```

Original comment by `corbinrs...@gmail.com` on 14 Feb 2012 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
I'm getting the below error. Is the update site working in your install of 
Eclipse? If so, what version of Eclipse are you testing it in? I'd be willing 
to install a different version of Eclipse.

Error I'm getting with 1.3.4.b:

org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter$TerminatingClassNot
FoundException: An error occurred while automatically activating bundle 
com.google.eclipse.javascript.jstestdriver.ui (13).
    at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:122)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:462)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:400)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:476)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:345)
    at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1207)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.ui.internal.WorkbenchPlugin$1.run(WorkbenchPlugin.java:268)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:264)
    at org.eclipse.ui.internal.registry.ViewDescriptor.createView(ViewDescriptor.java:63)
    at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:327)
    at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:229)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
    at org.eclipse.ui.internal.Perspective.showView(Perspective.java:2245)
    at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1145)
    at org.eclipse.ui.internal.WorkbenchPage$20.run(WorkbenchPage.java:3921)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3918)
    at org.eclipse.ui.handlers.ShowViewHandler.openView(ShowViewHandler.java:162)
    at org.eclipse.ui.handlers.ShowViewHandler.openOther(ShowViewHandler.java:105)
    at org.eclipse.ui.handlers.ShowViewHandler.execute(ShowViewHandler.java:73)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:293)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:476)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)
    at org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandlerService.java:241)
    at org.eclipse.ui.internal.ShowViewMenu$3.run(ShowViewMenu.java:187)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4165)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
Caused by: org.osgi.framework.BundleException: The activator 
com.google.eclipse.javascript.jstestdriver.ui.Activator for bundle 
com.google.eclipse.javascript.jstestdriver.ui is invalid
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:171)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:679)
    at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:299)
    at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
    at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:268)
    at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
    ... 65 more
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Maps
    at com.google.eclipse.javascript.jstestdriver.ui.Icons.<init>(Icons.java:48)
    at com.google.eclipse.javascript.jstestdriver.ui.Activator.<init>(Activator.java:36)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:166)
    ... 71 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:513)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 80 more

```

Original comment by `cfchris` on 14 Feb 2012 at 9:53

**Comment by GoogleCodeExporter** [comment]
```
Added in the missing jar (all of jstd, oddly enough). Try 1.3.4.c.
```

Original comment by `corbinrs...@gmail.com` on 15 Feb 2012 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the update. Now when I try to install (not update) it I get these 
errors:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.javascript, 
phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: 
osgi.bundle,com.google.eclipse.javascript.jstestdriver.config,1.3.4.b.
http://js-test-driver.googlecode.com/svn/update/plugins/com.google.eclipse.javas
cript.jstestdriver.config_1.3.4.b.jar
Artifact not found: 
osgi.bundle,com.google.eclipse.javascript.jstestdriver.core,1.3.4.b.
http://js-test-driver.googlecode.com/svn/update/plugins/com.google.eclipse.javas
cript.jstestdriver.core_1.3.4.b.jar
Artifact not found: 
osgi.bundle,com.google.eclipse.javascript.jstestdriver.ui,1.3.4.b.
http://js-test-driver.googlecode.com/svn/update/plugins/com.google.eclipse.javas
cript.jstestdriver.ui_1.3.4.b.jar
Artifact not found: osgi.bundle,com.google.javascript.jstestdriver,1.3.4.b.
http://js-test-driver.googlecode.com/svn/update/plugins/com.google.javascript.js
testdriver_1.3.4.b.jar


```

Original comment by `unigossi` on 15 Feb 2012 at 2:30

**Comment by GoogleCodeExporter** [comment]
```
Sigh. Try 1.3.4.e.
```

Original comment by `corbinrs...@gmail.com` on 15 Feb 2012 at 4:37

**Comment by GoogleCodeExporter** [comment]
```
yay that worked :) The choice for the conf files is not bound to the root 
folder of the project anymore and the eclipse project is revived.

Excellent job, Thank you very much for this.
```

Original comment by `unigossi` on 15 Feb 2012 at 11:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 15 Feb 2012 at 7:25
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Cory, thank you so much for getting this fixed.
```

Original comment by `cfchris` on 16 Feb 2012 at 3:08
