### ISSUE TITLE
JSTestDriver stopped working on Intellij 10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#176]
```
Running test caused stack trace below:

Error during dispatching of 
java.awt.event.MouseEvent[MOUSE_RELEASED,(462,59),absolute(458,55),button=1,modi
fiers=Button1,clickCount=1] on frame0: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V
java.lang.NoSuchMethodError: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V
    at com.google.jstestdriver.idea.TestRunnerState.execute(Unknown Source)
    at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:88)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:85)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:157)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:133)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:185)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:78)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:62)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:80)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:89)
    at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.actionPerformed(ExecutorRegistryImpl.java:229)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:153)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:129)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:289)
    at java.awt.Component.processEvent(Component.java:6032)
    at java.awt.Container.processEvent(Container.java:2041)
    at java.awt.Component.dispatchEventImpl(Component.java:4630)
    at java.awt.Container.dispatchEventImpl(Container.java:2099)
    at java.awt.Component.dispatchEvent(Component.java:4460)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
    at java.awt.Container.dispatchEventImpl(Container.java:2085)
    at java.awt.Window.dispatchEventImpl(Window.java:2478)
    at java.awt.Component.dispatchEvent(Component.java:4460)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:652)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:502)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:405)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:369)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

Original issue reported on code.google.com by `nomar.mo...@gmail.com` on 13 Dec 2010 at 8:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 11 Apr 2011 at 7:32
- Added labels: **IntelliJ**

**Comment by GoogleCodeExporter** [comment]
```
Plugin v1.3 or higher works correctly with IDEA v10 or higher.
Just update your plugin please.
```

Original comment by `Sergey.S...@gmail.com` on 10 May 2011 at 9:52
- Changed state: **Fixed**
