### ISSUE TITLE
jsTestDriver does not work at all in IDEA X 99.18 and hangs when running tests on v9.0.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#178]
```
More can be found about this problem here:
http://youtrack.jetbrains.net/issue/IDEA-63069

I am using IntelliJ 9.0.4 with jsTestRunner 1.2.2 and I repeatedly get hangs 
when I run all tests. It does not work at all with IDEA X 99.18.

Everything worked great at first in 9.0.4 until I got around to making 15 tests 
for 4 classes. I was testing against the latest versions of Chrome and Firefox. 

Now when I run my tests, there is a good chance Intellij IDEA just locks up 
completely. This happens consistently. The only way to stop it from hanging is 
to kill the browser, which gives control back to IDEA... but the more times I 
try and the run the tests, IDEA will lock up for good and I must kill the 
process. I have no clue how to fix this. I reboot Ubuntu just to see if that 
fixes it, but to no avail.

I also want to add that jsTestDriver works perfectly when I run the server and 
run the tests in 2 terminal windows, even when I use Opera, Firefox and Chrome 
at the same time. All 15 tests pass (45 tests total). 

If I run the server outside of IDEA and run the tests within IDEA, it still 
hangs. Cutting the jsTestDriver service relinquishes control most of the time. 
*This tells me the problem has something to do with the Unit testing windows 
and/or the communication with the plugin to report larger result sets.*

The only way I can stop IDEA from hanging is to run the basic Greeter tests, or 
other small test files. Once I include a test class with some meat to it, it 
fails. And the weird thing is... I can get it to
work sometimes, so I don't think the code I wrote is bad. 

So is the plugin broken with IDEA? Can anyone help me get this working with 
IDEA? It used to work just fine when I had 4 or 6 tests... but now that I give 
it anything remotely complex, it bombs.

Please help. I'd really like to use this tool. I'm working on a big project and 
not being able to use my IDE is going to be brutal.

And of course running jsTestDriver on IDEA X (99.18) results in the following 
exception:

com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V
java.lang.NoSuchMethodError: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V
    at com.google.jstestdriver.idea.TestRunnerState.execute(Unknown Source)
    at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:88)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:85)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:157)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:133)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:185)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:78)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:62)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:80)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:89)
    at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.actionPerformed(ExecutorRegistryImpl.java:229)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:524)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:444)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:197)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:492)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:405)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:369)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

Original issue reported on code.google.com by `ken.eger...@gmail.com` on 15 Dec 2010 at 8:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 11 Apr 2011 at 7:32
- Added labels: **IntelliJ**

**Comment by GoogleCodeExporter** [comment]
```
Ken, JsTestDriver plugin v1.3 or higher works correctly in IDEA v10.0 or 
higher. Just update it from plugin repository.
As for the plugin hanging, could you please provide the test sources (*.js and 
config), that meet this problem in IDEA v10.0 or higher and I'll create a 
separate bug (or you can create a bug with the attached test sources yourself).
This bug will be marked as Fixed.
```

Original comment by `Sergey.S...@gmail.com` on 10 May 2011 at 10:19
- Changed state: **Fixed**
