### ISSUE TITLE
JsTestDriver plugin fails on WebStorm 2 100.36

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#181]
```
What steps will reproduce the problem?
1. Launch WebStorm 2 build 100.36

What is the expected output? What do you see instead?
JSTestDriver Server plugin window is empty ... it should show controls to start 
the server and capture browsers.

What version of the product are you using? On what operating system?
Mac OSX 10.6, plugin v1.2.2, WebStorm 2 100.36 

Please provide any additional information below.
IDE notifies of plugin crash immediately upon launch with following trace:

com/intellij/peer/PeerFactory: com/intellij/peer/PeerFactory
java.lang.NoClassDefFoundError: com/intellij/peer/PeerFactory
    at com.google.jstestdriver.idea.JSTestDriverToolWindow.initToolWindow(Unknown Source)
    at com.google.jstestdriver.idea.JSTestDriverToolWindow.projectOpened(Unknown Source)
    at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:338)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:72)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:373)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(ProjectManagerImpl.java:145)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:988)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:382)
    at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:114)
    at com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryProjectsManager.java:60)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:297)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:101)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:183)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:175)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:167)
    at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:40)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:106)
    at $Proxy33.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication.loadProject(IdeaApplication.java:227)
    at com.intellij.idea.IdeaApplication.access$400(IdeaApplication.java:50)
    at com.intellij.idea.IdeaApplication$IdeStarter$3.run(IdeaApplication.java:192)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:652)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:506)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:405)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:369)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.peer.PeerFactory
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:70)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 38 more
```

Original issue reported on code.google.com by `ireney.b...@gmail.com` on 20 Dec 2010 at 10:41

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 11 Apr 2011 at 7:32
- Added labels: **IntelliJ**

**Comment by GoogleCodeExporter** [comment]
```
@Ireney: Please update plugin version to 1.3 or higher, it should work 
correctly.
```

Original comment by `Sergey.S...@gmail.com` on 10 May 2011 at 10:24
- Changed state: **Fixed**
