### ISSUE TITLE
IE8: 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#193]
```
What steps will reproduce the problem?
1. Capture IE8 Browser
2. After many runs or after the browser has been running for roughly a few 
hours.
3. Run tests via java -jar bin/JsTestDriver.jar --config 
tests/jsTestDriver.conf --reset --browserTimeout 10000 --tests all --testOutput 
_build/logs/jstestdriver

What is the expected output? What do you see instead?
The expected result is for the test to finish successfully.

I see this as the output in the end:

[exec] Microsoft Internet Explorer: Runner reset.
     [exec] ....Chrome: Runner reset.
     [exec] Unexpected Runner Condition: Failures during test run.
     [exec]  Use --runnerMode DEBUG for more information.
     [exec] 
     [exec] Test Errors:
     [exec]     atFailures during test run.
     [exec]     at com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:108)
     [exec]     at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
     [exec]     at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:85)
     [exec] Caused by:
     [exec] com.google.jstestdriver.browser.BrowserPanicException: Browser Microsoft Internet Explorer 8.0 Windows
     [exec] During execution of command

What version of the product are you using? On what operating system?
v1.2.2 on Linux version 2.6.31-22-server (buildd@allspice) (gcc version 4.4.1 
(Ubuntu 4.4.1-4ubuntu9) ) #69-Ubuntu SMP Wed Nov 24 09:25:59 UTC 2010


Please provide any additional information below.

In IE8 it shows a JS error:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Timestamp: Thu, 27 Jan 2011 16:32:52 UTC


Message: 'undefined' is null or not an object
Line: 1
Char: 8034
Code: 0
URI: http://build:4224/slave/23/runner.js



```

Original issue reported on code.google.com by `duozh...@gmail.com` on 27 Jan 2011 at 4:42

**Comment by GoogleCodeExporter** [comment]
```
My apologies for the title. I can't edit the title after submitting the issue. 
Please note that it took roughly 2 hours for the test run to throw the 
exception. 

Please let me know if you need any information and how I can somehow patch this 
issue? Preventing my CI server from reporting failures properly.
```

Original comment by `duozh...@gmail.com` on 27 Jan 2011 at 4:45

**Comment by GoogleCodeExporter** [comment]
```
I re-ran the tests after this error, and all is well. A successful test run. 
Very intermittent results, but does happen a couple times a day.
```

Original comment by `duozh...@gmail.com` on 27 Jan 2011 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
I think I got this licked in 1.3.0

Please verify.
```

Original comment by `corbinrs...@gmail.com` on 14 Feb 2011 at 4:30
- Changed state: **Fixed**
