### ISSUE TITLE
1.3.0 attempts to hit /proxy when a proxy: section is defined in the config file. Known workaround: pass --serverHandlerPrefix=jstd

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#198]
```
What steps will reproduce the problem?
1. Running 1.3.0 server with a proxy: config section causes:
java.lang.RuntimeException: Connection error on: 
sun.net.www.protocol.http.HttpURLConnection:http://127.0.0.1:7777/proxy
    at com.google.jstestdriver.HttpServer.postJson(HttpServer.java:124)
    at com.google.jstestdriver.action.ConfigureProxyAction.run(ConfigureProxyAction.java:43)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:88)
Caused by: java.io.FileNotFoundException: http://127.0.0.1:7777/proxy
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1267)
    at com.google.jstestdriver.HttpServer.postJson(HttpServer.java:120)
    ... 3 more
java.lang.RuntimeException: Connection error on: 
sun.net.www.protocol.http.HttpURLConnection:http://127.0.0.1:7777/proxy
    at com.google.jstestdriver.HttpServer.postJson(HttpServer.java:124)
    at com.google.jstestdriver.action.ConfigureProxyAction.run(ConfigureProxyAction.java:43)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:88)
Caused by: java.io.FileNotFoundException: http://127.0.0.1:7777/proxy
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1267)
    at com.google.jstestdriver.HttpServer.postJson(HttpServer.java:120)
    ... 3 more
Unexpected Runner Condition: Connection error on: 
sun.net.www.protocol.http.HttpURLConnection:http://127.0.0.1:7777/proxy


What is the expected output? What do you see instead?
N/A

What version of the product are you using? On what operating system?
ANY

Please provide any additional information below.

Workaround: pass --serverHandlerPrefix=jstd

```

Original issue reported on code.google.com by `rdio...@google.com` on 17 Feb 2011 at 10:42

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r890.
```

Original comment by `robertsd...@gmail.com` on 17 Feb 2011 at 11:14
- Changed state: **Fixed**
