### ISSUE TITLE
IntelliJ IDEA 10.0.2 not compatible with plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#209]
```
What steps will reproduce the problem?
1. Downloaded and installed jsTestDriver plugin.
2. Opened panel, started jsTestDriver server and captured browser.
3. Created a new run configuration, pointing to jsTestDriver.conf file
4. Clicked run, the following error was generated:

com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.(Lcom/
intellij/execution/configurations/RuntimeConfiguration;)V: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.(Lcom/
intellij/execution/configurations/RuntimeConfiguration;)V
java.lang.NoSuchMethodError: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.(Lcom/
intellij/execution/configurations/RuntimeConfiguration;)V
at com.google.jstestdriver.idea.TestRunnerState.execute(Unknown Source)
at 
com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgra
mRunner.java:88)
at 
com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunn
er.java:85)
at 
com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java
:157)
at 
com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:9
6)
at com.intellij.openapi.project.DumbService$1.run(DumbService.java:76)
at 
com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocat
or.java:332)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:652)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:505)
at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:404)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:368)
at 
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269
)
at 
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
at 
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174
)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)


What version of the product are you using? On what operating system?
* build 103.72
* IDEA 10.0.2
* Windows 7
* JDK 1.6.0_23

```

Original issue reported on code.google.com by `alexea...@google.com` on 1 Mar 2011 at 6:45

**Comment by GoogleCodeExporter** [comment]
```
This bug is fixed in JsTestDriver IDEA plugin v1.3 or later.
```

Original comment by `Sergey.S...@gmail.com` on 28 Jun 2011 at 2:24
- Changed state: **Fixed**
