### ISSUE TITLE
Browser is not captured on latest version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#211]
```
What steps will reproduce the problem?
1. run "java -jar jsTestDriver-1.3.1.jar --port 9876 --runnerMode DEBUG
2. Go to http://localhost:9876 & click the 'Capture this browser' link

What is the expected output? What do you see instead?

The screen with a green bar at the top indicating the server is running & 
output on the command-line showing the requests fired.

I see the error below and the screen goes to this URL but reads blank:

http://localhost:9876/slave/id/1299166225673/page/CONSOLE/mode/quirks/timeout/30
000/upload_size/50/rt/CLIENT

What version of the product are you using? On what operating system?

version: jsTestDriver-1.3.1 (also found this with 1.3.0)
OS: Max OSX 10.5.8
Browsers tried: Firefox, Google chrome, Opera, Safari
Java info: 

java version "1.5.0_16"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_16-b06-284)
Java HotSpot(TM) Client VM (build 1.5.0_16-133, mixed mode, sharing)


Please provide any additional information below.

Using the older jsTestDriver-1.2.2.jar works fine without the error below:

Mar 3, 2011 3:23:42 PM 
com.google.jstestdriver.requesthandlers.RequestDispatcher dispatch
SEVERE: Error in request {}
com.google.inject.ProvisionException: Guice provision errors:

1) Error in custom provider, java.lang.RuntimeException: 
java.lang.reflect.InvocationTargetException
  at com.google.jstestdriver.server.handlers.JstdHandlersModule.providePageRequest(JstdHandlersModule.java:200)
  while locating com.google.jstestdriver.server.handlers.pages.SlavePageRequest
    for parameter 2 at com.google.jstestdriver.server.handlers.SlaveResourceHandler.<init>(SlaveResourceHandler.java:41)
  while locating com.google.jstestdriver.server.handlers.SlaveResourceHandler
  while locating com.google.jstestdriver.requesthandlers.RequestHandler annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=57)

1 error
    at com.google.inject.InjectorImpl$4.get(InjectorImpl.java:767)
    at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:89)
    at com.google.jstestdriver.requesthandlers.RequestDispatcher.dispatch(RequestDispatcher.java:68)
    at com.google.jstestdriver.requesthandlers.RequestHandlerServlet.service(RequestHandlerServlet.java:50)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:389)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:864)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)
Caused by: java.lang.RuntimeException: 
java.lang.reflect.InvocationTargetException
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:106)
    at com.google.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:48)
    at com.google.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
    at com.google.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
    at com.google.inject.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:111)
    at com.google.inject.FactoryProxy.get(FactoryProxy.java:56)
    at com.google.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
    at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:811)
    at com.google.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
    at com.google.jstestdriver.requesthandlers.RequestScope$1.get(RequestScope.java:76)
    at com.google.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:48)
    at com.google.inject.InjectorImpl$4$1.call(InjectorImpl.java:758)
    at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:804)
    at com.google.inject.InjectorImpl$4.get(InjectorImpl.java:754)
    ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:101)
    ... 31 more
Caused by: java.lang.NoSuchMethodError: java.lang.String.isEmpty()Z
    at com.google.jstestdriver.util.ParameterParser.getParameterMap(ParameterParser.java:59)
    at com.google.jstestdriver.server.handlers.JstdHandlersModule.providePageRequest(JstdHandlersModule.java:200)
    ... 36 more
Mar 3, 2011 3:24:24 PM com.google.jstestdriver.SlaveBrowser isAlive
FINE: Browser dead: SlaveBrowser(browserInfo=Firefox 3.6.13 Mac OS,
    id=1299165821975,
    sinceLastCheck=-1.0s,
    timeout=30000)
Mar 3, 2011 3:24:24 PM com.google.jstestdriver.browser.BrowserReaper run
FINE: Reaping dead SlaveBrowser(browserInfo=Firefox 3.6.13 Mac OS,
    id=1299165821975,
    sinceLastCheck=-1.0s,
    timeout=30000).

Thanks for the help,

Tom
```

Original issue reported on code.google.com by `tombaro...@gmail.com` on 3 Mar 2011 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
Please upgrade to Java 1.6.

Let me know if this is problem, though it really shouldn't be.
```

Original comment by `corbinrs...@gmail.com` on 6 Mar 2011 at 8:54
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
That's exactly the problem, runs fine with Java 1.6. Thanks for the help, much 
appreciated.

For anyone upgrading on Mac, it's useful to know this: 
http://adam.shand.net/archives/2009/selecting_java_version_on_mac_osx_10_5_leopa
rd/
```

Original comment by `tombaro...@gmail.com` on 11 Mar 2011 at 9:22
