### ISSUE TITLE
Eclipse plugin installation needs to be clarified.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#214]
```
What steps will reproduce the problem?
1. Choose "http://js-test-driver.googlecode.com/svn/update/" as a plugin 
location in Eclipse.
2. Select "JsTestDriver Plugin for Eclipse/JS Test Driver 1.1.1.c" as the 
plugin to install
3. Try to run a test; it will hang. At least one other person has had this 
problem.

What is the expected output? What do you see instead?
The test hangs when trying to do something with a delegate; in Eclipse, this is 
reported as a hang 57% through the test run. At least one other person has 
reported this problem.


What version of the product are you using? On what operating system?
JS Test Driver 1.1.1.c on OS X 10.6.6.


Please provide any additional information below.
The problem can be resolved by instead installing "Uncategorized/JS Test Driver 
1.1.1.e" from the same site. Unless there's a reason for having the two 
versions available, v 1.1.1.c should be removed and 1.1.1.e should be moved 
from "Uncategorized" to "JS Test Driver". If it is necessary to have both 
versions, there should be a comment that shows up in the Eclipse installation 
box explaining the purpose of the given version.

Thanks,
Ken McDonald

```

Original issue reported on code.google.com by `ykken...@gmail.com` on 9 Mar 2011 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
Have the same problem with SpringSource Tool Suite. I have 1.1.1.e version.

Error I am getting:

!ENTRY com.google.eclipse.javascript.jstestdriver.ui 4 0 2011-10-14 15:39:37.062
!MESSAGE Runtime exception happened in JS Test Driver
!STACK 0

Test Errors:
    atFailures during test run.
    at com.google.jstestdriver.BrowserActionsRunner.run(BrowserActionsRunner.java:108)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:56)
    at com.google.eclipse.javascript.jstestdriver.ui.launch.JsTestDriverLaunchConfigurationDelegate.launch(JsTestDriverLaunchConfigurationDelegate.java:65)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:854)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:703)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:928)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1132)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by:
    atcom.google.jstestdriver.browser.BrowserPanicException: Browser Firefox 7.0.1 Windows
During Loading files into the browser.
```

Original comment by `alexey.s.grigoriev@gmail.com` on 14 Oct 2011 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
It seems that the problem occurs only with Firefox 7.0.1
```

Original comment by `alexey.s.grigoriev@gmail.com` on 14 Oct 2011 at 11:51

**Comment by GoogleCodeExporter** [comment]
```
Have the same problem in Eclipse for the most recent versions of IE 9, Firefox, 
Chrome, Safari (as of ocotber 22nd, 2011).
If I run the tests from the command line (outside of Eclipse), I succeed in an 
unexpected way: If the tests provide browser output it can be seen in the 
browsers. However on the command line it is reported that no tests were run.
```

Original comment by `hel...@hellerim.de` on 22 Oct 2011 at 7:44
