### ISSUE TITLE
Eclipse Freeze if you are trying to run a test.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#215]
```
What steps will reproduce the problem?
1. Create a demo project as in the video shown here: 
http://theshyam.com/2009/08/micro-update/
2. Start server, start Browser, capture, bar goes green in eclipse.
3. "Run as" -> "JS Test Driver Test" 

What is the expected output? What do you see instead?
Tests should be running and some result should be shown.
Instead Eclipse is completely freezing and the only solution is to kill the 
browser and wait some time. Oh, and clicking like a retarded on eclipse helps 
too. :/

What version of the product are you using? On what operating system?
Version: Helios Service Release 1
Build id: 20100917-0705
js-test-driver eclipse plugin is: 1.1.1.c

Ubuntu Linux 64bit, JVM 64 bit.

Please provide any additional information below.

Logged Infos: 
Mar 15, 2011 8:22:26 AM com.google.jstestdriver.ServerStartupAction run
INFO: Starting server...
Mar 15, 2011 8:22:26 AM org.mortbay.log.Slf4jLog info
INFO: Logging to org.slf4j.impl.JDK14LoggerAdapter(org.mortbay.log) via 
org.mortbay.log.Slf4jLog
Mar 15, 2011 8:22:26 AM org.mortbay.log.Slf4jLog info
INFO: jetty-6.1.x
Mar 15, 2011 8:22:26 AM org.mortbay.log.Slf4jLog info
INFO: Transparent ProxyServlet @ forward to http://localhost:42442
Mar 15, 2011 8:22:26 AM org.mortbay.log.Slf4jLog info
INFO: Started SocketConnector@0.0.0.0:42442
Mar 15, 2011 8:22:31 AM com.google.jstestdriver.BrowserHunter captureBrowser
INFO: Browser Captured: Chrome version 10.0.648.133 (1)
Mar 15, 2011 8:31:19 AM com.google.jstestdriver.BrowserHunter captureBrowser
INFO: Browser Captured: Chrome version 10.0.648.133 (2)
Mar 15, 2011 8:31:22 AM com.google.jstestdriver.BrowserHunter captureBrowser
INFO: Browser Captured: Chrome version 10.0.648.133 (3)
Mar 15, 2011 8:31:32 AM com.google.jstestdriver.CommandTask shouldPanic
SEVERE: Browser not found : 
{"browserInfo":{"id":1,"name":"Chrome","version":"10.0.648.133","os":"Linux"}}
 during: File upload reset 
 Exception: com.google.jstestdriver.browser.BrowserPanicException: Browser Chrome 10.0.648.133 Linux
During File upload reset
Mar 15, 2011 8:32:50 AM com.google.jstestdriver.ServerStartupAction run
INFO: Starting server...
Mar 15, 2011 8:32:50 AM org.mortbay.log.Slf4jLog info
INFO: jetty-6.1.x
Mar 15, 2011 8:32:50 AM org.mortbay.log.Slf4jLog info
INFO: Transparent ProxyServlet @ forward to http://localhost:42442
Mar 15, 2011 8:32:50 AM org.mortbay.log.Slf4jLog info
INFO: Started SocketConnector@0.0.0.0:42442
Mar 15, 2011 8:33:04 AM com.google.jstestdriver.BrowserHunter captureBrowser
INFO: Browser Captured: Chrome version 10.0.648.133 (4)
Mar 15, 2011 8:33:31 AM com.google.jstestdriver.ActionRunner runActions
INFO: 
Mar 15, 2011 8:33:31 AM com.google.jstestdriver.ActionRunner runActions
INFO: 
Mar 15, 2011 8:34:33 AM org.mortbay.log.Slf4jLog warn
SEVERE: /cmd
java.lang.NullPointerException
    at com.google.eclipse.javascript.jstestdriver.core.model.SlaveBrowserRootData.update(SlaveBrowserRootData.java:78)
    at java.util.Observable.notifyObservers(Observable.java:142)
    at com.google.jstestdriver.CapturedBrowsers.removeSlave(CapturedBrowsers.java:68)
    at com.google.jstestdriver.CommandServlet.getResponse(CommandServlet.java:75)
    at com.google.jstestdriver.CommandServlet.streamResponse(CommandServlet.java:111)
    at com.google.jstestdriver.CommandServlet.doGet(CommandServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:389)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:864)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)
```

Original issue reported on code.google.com by `Florian....@googlemail.com` on 15 Mar 2011 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
Ok, after updating to 1.1.1.e everything works...

```

Original comment by `Florian....@googlemail.com` on 15 Mar 2011 at 8:18
