### ISSUE TITLE
NullPointerException in FileInfo when running tests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#220]
```
Some tests that were working on 1.3.1 are failing on 1.3.2. See attached file 
for debug log.
Our tests were failing, so I tried the jstestdriver-maven-plugin sample-app, 
which works on 1.3.1 and fails on 1.3.2.


Apr 1, 2011 8:02:05 AM 
com.google.jstestdriver.server.handlers.BrowserQueryResponseHandler handleIt
FINEST: Browser Query Post:
    path:1301666524796
    response:{"type":"FILE_LOAD_RESULT","response":"{\"loadedFiles\":[{\"file\":{\"fileSrc\":\"/test/_/_/main/webapp/js/Person.js\",\"timestamp\":1271463427000},\"success\":true,\"message\":\"\",\"elapsed\":5},{\"file\":{\"fileSrc\":\"/test/_/webapp/js/PersonTest.js\",\"timestamp\":1271463427000},\"success\":true,\"message\":\"\",\"elapsed\":9}]}","browser":{"id":1301666524796}}
    done:true
    responseId:null
Apr 1, 2011 8:02:05 AM 
com.google.jstestdriver.server.handlers.BrowserQueryResponseHandler 
serviceBrowser
FINE: response type: FILE_LOAD_RESULT
Apr 1, 2011 8:02:05 AM 
com.google.jstestdriver.requesthandlers.RequestDispatcher dispatch
SEVERE: Error in request {}
java.lang.NullPointerException
    at com.google.jstestdriver.FileInfo.equals(FileInfo.java:137)
    at java.util.HashMap.put(HashMap.java:376)
    at java.util.HashSet.add(HashSet.java:200)
    at com.google.jstestdriver.server.handlers.BrowserQueryResponseHandler.serviceBrowser(BrowserQueryResponseHandler.java:145)
    at com.google.jstestdriver.server.handlers.BrowserQueryResponseHandler.service(BrowserQueryResponseHandler.java:104)
    at com.google.jstestdriver.server.handlers.BrowserQueryResponseHandler.handleIt(BrowserQueryResponseHandler.java:87)
    at com.google.jstestdriver.requesthandlers.RequestDispatcher.dispatch(RequestDispatcher.java:68)
    at com.google.jstestdriver.requesthandlers.RequestHandlerServlet.service(RequestHandlerServlet.java:50)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:389)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:879)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:747)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)
Apr 1, 2011 8:02:05 AM 
com.google.jstestdriver.requesthandlers.RequestDispatcher dispatch

```

Original issue reported on code.google.com by `RedB...@gmail.com` on 1 Apr 2011 at 2:07

Attachments:
- [jstd.txt](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-220/comment-0/jstd.txt)

**Comment by GoogleCodeExporter** [comment]
```
Can't repro.
```

Original comment by `corbinrs...@gmail.com` on 29 Sep 2011 at 5:51
- Changed state: **Invalid**
