### ISSUE TITLE
Jasmine-only tests are not executed from IDEA

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#252]
```
What steps will reproduce the problem?
1. Install jsTestDriver with jasmine and jasmine integration
2. create few tests using only jasmine
3. Configure IntelliJ Idea plugin to run your tests

What is the expected output? What do you see instead?
All test should be normally executed. However plugin showing following output: 

com.google.jstestdriver.FailureException: No tests executed.
    at com.google.jstestdriver.FailureCheckerAction.run(FailureCheckerAction.java:50)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
    at com.google.jstestdriver.idea.TestRunner.execute(TestRunner.java:113)
    at com.google.jstestdriver.idea.TestRunner.execute(TestRunner.java:79)
    at com.google.jstestdriver.idea.TestRunner.main(TestRunner.java:192)


So it looks like plugin doesn't understand jasmine tests.
What version of the product are you using? On what operating system?
IntelliJ IDEA 10.5.1, jsTestDriver Plugin 1.3.5

Thanks in advance
```

Original issue reported on code.google.com by `volodymy...@gmail.com` on 7 Jul 2011 at 2:59

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the feedback.
This issue is already fixed in development.
At the moment jasmine test structure IDE integration is being developed 
(Ctrl+Shift+F10 shortcut support when caret inside test method body). In a fact 
it requires a little more redesign affecting other assert frameworks.
Fixed plugin release version is planned in two month.
```

Original comment by `Sergey.S...@gmail.com` on 8 Jul 2011 at 9:33
- Changed state: **Started**
- Added labels: **IntelliJ**

**Comment by GoogleCodeExporter** [comment]
```
Thanks. Looking forward for new version.
```

Original comment by `volodymy...@gmail.com` on 8 Jul 2011 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Issue 258 has been merged into this issue.
```

Original comment by `Sergey.S...@gmail.com` on 1 Aug 2011 at 9:09

**Comment by GoogleCodeExporter** [comment]
```
Fixed version of the plugin is 1.3.6.
```

Original comment by `Sergey.S...@gmail.com` on 28 Sep 2011 at 4:39
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks. Just verified that now everything works as expected.
```

Original comment by `volodymy...@gmail.com` on 28 Sep 2011 at 8:05

**Comment by GoogleCodeExporter** [comment]
```
Any idea when an update will be available for download? Latest .jar file I see 
in the downloads page is 1.3.3b
```

Original comment by `arthura...@gmail.com` on 7 Oct 2011 at 1:09

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Updated JsTestDriver plugin version is already uploaded to the plugin 
repository.
```

Original comment by `Sergey.S...@gmail.com` on 7 Oct 2011 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
Ah, sorry. I was using an older version of PHP Storm, and it wouldn't download 
the latest version. Updated my IDE and I now have the new version of the plugin.
```

Original comment by `arthura...@gmail.com` on 7 Oct 2011 at 12:21
