### ISSUE TITLE
--browser flag for Safari on OSX tries to load file path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#253]
```
Issuing this command:

java -jar JsTestDriver-1.3.2.jar --port 4224 --browser 
/Applications/Safari.app/Contents/MacOS/Safari

...Loads the browser successfully, but it tries to load a file path, eg: 

file:///FOLDER/PATH/TO/JAR/http:/localhost:[PORT]/capture/id/1310546478471/timeo
ut/30000/upload_size/50

This results in the following stack trace in the command line:

java.lang.RuntimeException: java.util.concurrent.ExecutionException: 
java.lang.RuntimeException: Could not start browser CommandLineBrowserRunner [
browserPath=/Applications/Safari.app/Contents/MacOS/Safari,
process=java.lang.UNIXProcess@37c2ec05,
 process log={
error:
[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@
5e1558dc
input:

}] in 30
    at com.google.jstestdriver.BrowserStartupAction.run(BrowserStartupAction.java:75)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
    at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:86)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: 
Could not start browser CommandLineBrowserRunner [
browserPath=/Applications/Safari.app/Contents/MacOS/Safari,
process=java.lang.UNIXProcess@37c2ec05,
 process log={
error:
[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@
5e1558dc
input:

}] in 30
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
    at java.util.concurrent.FutureTask.get(FutureTask.java:83)
    at com.google.jstestdriver.BrowserStartupAction.run(BrowserStartupAction.java:71)
    ... 2 more
Caused by: java.lang.RuntimeException: Could not start browser 
CommandLineBrowserRunner [
browserPath=/Applications/Safari.app/Contents/MacOS/Safari,
process=java.lang.UNIXProcess@37c2ec05,
 process log={
error:
[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@
5e1558dc
input:

}] in 30
    at com.google.jstestdriver.browser.BrowserControl.captureBrowser(BrowserControl.java:68)
    at com.google.jstestdriver.BrowserStartupAction$1.call(BrowserStartupAction.java:63)
    at com.google.jstestdriver.BrowserStartupAction$1.call(BrowserStartupAction.java:61)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Unexpected Runner Condition: java.util.concurrent.ExecutionException: 
java.lang.RuntimeException: Could not start browser CommandLineBrowserRunner [
browserPath=/Applications/Safari.app/Contents/MacOS/Safari,
process=java.lang.UNIXProcess@37c2ec05,
 process log={
error:
[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@5e1558dc[B@
5e1558dc
input:

}] in 30
 Use --runnerMode DEBUG for more information.


...Before you ask, yes, you have to reference the browser using the full path 
to the executable within the 'app' bundle, which is also a tad annoying.
```

Original issue reported on code.google.com by `luke.dy...@flyinganvil.co.uk` on 13 Jul 2011 at 8:45
- Merged into: #97

**Comment by GoogleCodeExporter** [comment]
```
I'm seeing the same issue on OS X Lion
```

Original comment by `bradgr...@google.com` on 9 Aug 2011 at 6:10

**Comment by GoogleCodeExporter** [comment]
```
dupe of #97

See http://code.google.com/p/js-test-driver/issues/detail?id=97#c8 for 
workaround
```

Original comment by `imi...@google.com` on 4 Nov 2011 at 6:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 28 Dec 2011 at 9:19
- Changed state: **Duplicate**
