### ISSUE TITLE
Better error report formatting in the JsTD view

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#26]
```
Currently, an error looks like this:

Message : {"stack":"AssertError\n    at
http://localhost:9999/slave/1/runner.js:1:85\n    at [object
Object].testInit
(http://localhost:9999/test//Users/corysmith/repos/trunk/JsTestDriver/src-test/c
om/google/jstestdriver/coverage/javascript/LCOVTest.js:4:2)\n
   at [object Object].runTest_
(http://localhost:9999/slave/1/runner.js:244:29)\n    at [object
Object].runTestConfiguration
(http://localhost:9999/slave/1/runner.js:213:20)\n    at [object
Object].runTestConfiguration
(http://localhost:9999/slave/1/runner.js:308:25)\n    at [object
Object].dispatch_ (http://localhost:9999/slave/1/runner.js:1:5813)\n    at
[object Object].runTestConfiguration
(http://localhost:9999/slave/1/runner.js:1:6224)\n    at [object
Object].runTestConfiguration_
(http://localhost:9999/slave/1/runner.js:1:12239)\n    at [object
Object].runTests (http://localhost:9999/slave/1/runner.js:1:12039)\n    at
[object Object].runTestCases_
(http://localhost:9999/slave/1/runner.js:1:18971)","name":"AssertError"}
Log : 


It would be highly improved if it looked like this:

AssertError
   at http://localhost:9999/slave/1/runner.js:1:85
   at [object Object].testInit
(http://localhost:9999/test//Users/corysmith/repos/trunk/JsTestDriver/src-test/c
om/google/jstestdriver/coverage/javascript/LCOVTest.js:4:2)
   at [object Object].runTest_ (http://localhost:9999/slave/1/runner.js:244:29)
   at [object Object].runTestConfiguration
(http://localhost:9999/slave/1/runner.js:213:20)
   at [object Object].runTestConfiguration
(http://localhost:9999/slave/1/runner.js:308:25)
   at [object Object].dispatch_
(http://localhost:9999/slave/1/runner.js:1:5813)
   at [object Object].runTestConfiguration
(http://localhost:9999/slave/1/runner.js:1:6224)
   at [object Object].runTestConfiguration_
(http://localhost:9999/slave/1/runner.js:1:12239)
   at [object Object].runTests
(http://localhost:9999/slave/1/runner.js:1:12039)
   at [object Object].runTestCases_
(http://localhost:9999/slave/1/runner.js:1:18971)

Log : 
```

Original issue reported on code.google.com by `corbinrs...@gmail.com` on 17 Aug 2009 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
Fixed to use JS Test Driver's pretty printing in the log, so no more of that 
json string. 
Pushed out to the update site with revision r272
```

Original comment by `shyamseshadri` on 20 Aug 2009 at 6:08
- Changed state: **Verified**
