### ISSUE TITLE
Output not displayed in console in IDEA plugin in PhpStorm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#275]
```
What steps will reproduce the problem?
1. install jsTestDriver plugin in PhpStorm
2. Start jsTestDriver server through plugin
3. Create run configuration pointing to conf file
4. run the new runner

What is the expected output? What do you see instead?
Most of the output that does show up when interacting with the 1.3.3b jar 
directly from the command line does not show up in the IDE plugin when running 
the server through the plugin, so the feedback needed for TDD is not present 
with this approach.

What version of the product are you using? On what operating system?
Version 1.3.6, 28 September 2011 (build on JsTestDriver v1.3.2)
in PhpStorm 2.1.5
on Mac OSX 10.6.8


Please provide any additional information below.
I had tried to get started with jsTestDriver before but was working on a 
project with enough legacy code that making the transition would have been too 
much effort. I got new motivation to try again with a different project, but 
getting things set up and working was a struggle. The lack of output tops off 
the frustration, but I'm hoping there is a quick fix for this one.
```

Original issue reported on code.google.com by `ad...@travi.org` on 3 Oct 2011 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
Could you please clarify what kind of output you expect?
Attaching sample JavaScript test with expected output will be enough.
Thanks!
```

Original comment by `Sergey.S...@gmail.com` on 4 Oct 2011 at 6:53
- Added labels: **IntelliJ**

**Comment by GoogleCodeExporter** [comment]
```
when running directly against a jar from the command line I get descriptive 
output like this:

java -jar /Users/travi/Downloads/JsTestDriver-1.3.3b.jar --tests all
.........FFFFF...............FFFFF......
Total 40 tests (Passed: 30; Fails: 10; Errors: 0) (39.00 ms)
  Firefox 7.0.1 Mac OS: Run 20 tests (Passed: 15; Fails: 5; Errors 0) (24.00 ms)
    Choose Version.test Links added to page failed (1.00 ms): AssertError: undefinedexpected "Switch to version" but was ""
      ("","Switch to version")@http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:9
      ()@http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:36
      ()@http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40

    Choose Version.test Mobile link shown when desktop version active failed (2.00 ms): AssertError: undefinedexpected "mobile" but was ""
      ("","mobile")@http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:9
      ()@http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:55
      ()@http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40

    Choose Version.test Desktop link shown when mobile version active failed (2.00 ms): AssertError: undefinedexpected "desktop" but was ""
      ("","desktop")@http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:9
      ()@http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:66
      ()@http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40

    Choose Version.test Switch to Desktop version failed (2.00 ms): AssertError: undefinedexpected "desktop" but was "mobile"
      ("mobile","desktop")@http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:9
      ()@http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:82
      ()@http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40

    Choose Version.test Switch to Mobile version failed (2.00 ms): AssertError: reloads to get proper resources expected true but was false
      (false,"reloads to get proper resources")@http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:53
      ()@http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:101
      ()@http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40

  Chrome 14.0.835.186 Mac OS: Run 20 tests (Passed: 15; Fails: 5; Errors 0) (39.00 ms)
    Choose Version.test Links added to page failed (15.00 ms): AssertError: undefinedexpected "Switch to version" but was ""
      AssertError: undefinedexpected "Switch to version" but was ""
          at http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:8:13
          at Object.<anonymous> (http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:36:9)
          at [object Object].test Links added to page (http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40:15)

    Choose Version.test Mobile link shown when desktop version active failed (2.00 ms): AssertError: undefinedexpected "mobile" but was ""
      AssertError: undefinedexpected "mobile" but was ""
          at http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:8:13
          at Object.<anonymous> (http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:55:9)
          at [object Object].test Mobile link shown when desktop version active (http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40:15)

    Choose Version.test Desktop link shown when mobile version active failed (1.00 ms): AssertError: undefinedexpected "desktop" but was ""
      AssertError: undefinedexpected "desktop" but was ""
          at http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:8:13
          at Object.<anonymous> (http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:66:9)
          at [object Object].test Desktop link shown when mobile version active (http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40:15)

    Choose Version.test Switch to Desktop version failed (0.00 ms): AssertError: undefinedexpected "desktop" but was "mobile"
      AssertError: undefinedexpected "desktop" but was "mobile"
          at http://localhost:9876/test/client/js/qunit/QUnitAdapterExtensions.js:8:13
          at Object.<anonymous> (http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:80:9)
          at [object Object].test Switch to Desktop version (http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40:15)

    Choose Version.test Switch to Mobile version failed (0.00 ms): AssertError: reloads to get proper resources expected true but was false
      AssertError: reloads to get proper resources expected true but was false
          at http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:53:9
          at Object.<anonymous> (http://localhost:9876/test/php/framework/test/js/tests/enhancementVersion/chooseVersion.qunit:101:9)
          at [object Object].test Switch to Mobile version (http://localhost:9876/test/client/js/qunit/QUnitAdapter.js:40:15)

Tests failed: Tests failed. See log for details.

When I run from the IDEA plugin in PhpStorm is get this:


Testing started at 8:35 PM ...

AssertError: 

AssertError: 

AssertError: 

AssertError: 

AssertError: 

AssertError: 

AssertError: 

AssertError: 

AssertError: 

AssertError: 
```

Original comment by `travi...@gmail.com` on 7 Oct 2011 at 1:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `Sergey.S...@gmail.com` on 7 Oct 2011 at 4:21
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Starting from v1.3.7 JsTestDriver plugin is built against 
JsTestDriver-1.3.3b.jar.
Please update from plugin repository.
```

Original comment by `Sergey.S...@gmail.com` on 7 Oct 2011 at 4:25
- Changed state: **Fixed**
