### ISSUE TITLE
The parameter --dryRunFor TestCase name does not work properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#302]
```
What steps will reproduce the problem?
1. Go to sample 'Hello World' project.
2. java -jar JsTestdriver.jar --port 42442 --browser <path to browser>
3.java -jar JsTestdriver.jar --dryRunFor GreeterTest --server 
http://127.0.0.1:42442

What is the expected output? What do you see instead?
Expected: Firefox 8.0.1: 1 tests [GreeterTest.testGreet]
Instead see: java.lang.NullPointerException
        at com.google.jstestdriver.DryRunAction$DryRunActionResponseStream.stream(DryRunAction.java:64)
        at com.google.jstestdriver.AggregatingResponseStreamFactory$AggregatingResponseStream.stream(AggregatingResponseStreamFactory.java:98)
        at com.google.jstestdriver.CommandTask.run(CommandTask.java:138)
        at com.google.jstestdriver.JsTestDriverClientImpl.sendCommand(JsTestDriverClientImpl.java:103)
        at com.google.jstestdriver.JsTestDriverClientImpl.dryRunFor(JsTestDriverClientImpl.java:159)


What version of the product are you using? On what operating system?
trunk

Please provide any additional information below.
The server sends following json: 
{"numTests":1,"testNames":["GreeterTest.testGreet"]}

Classes DryRunAction and DryRunInfo expect following JSON: 
{"numTests":1,"testNames":[JSON for TestCase]}



```

Original issue reported on code.google.com by `m.jurcov...@gmail.com` on 2 Dec 2011 at 12:41

**Comment by GoogleCodeExporter** [comment]
```
Attached patch changes the class DryRunInfo to match with incoming JSON. 
```

Original comment by `m.jurcov...@gmail.com` on 2 Dec 2011 at 12:43

Attachments:
- [patch04-dryRunForConcreteTestCases.patch](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-302/comment-1/patch04-dryRunForConcreteTestCases.patch)

**Comment by GoogleCodeExporter** [comment]
```
1.) Ignore previous comment please, I just found out that it will be better to 
change CommandExecutor.js to send list of test cases instead of test names. 

2.) --dryRunFor all does not work either, I will try to fix them both at the 
same time.


```

Original comment by `m.jurcov...@gmail.com` on 2 Dec 2011 at 1:04

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1095.
```

Original comment by `corbinrs...@gmail.com` on 2 Dec 2011 at 9:26
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Did the clean up and cleaned out the bitrot.
```

Original comment by `corbinrs...@gmail.com` on 2 Dec 2011 at 9:26
