### ISSUE TITLE
how to configure log file format??

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#320]
```
What steps will reproduce the problem?
1.start server
2.capture two browser: FF3, Chrome14
3.java -jar JsTestDriver-1.3.2.jar --runnerMode PROFILE --reset --tests all > 
.\test-result.txt
4.no way to configure test result format in test-result.txt

What is the expected output? What do you see instead?
I don't need browser reset information, execution time, error stacktrace etc.

expect : in test-result.txt:

Firefox 3.6.25      Windows : F.F.
Chrome 14.0.814.0   Windows : F.F.

Total 8 tests (Passed: 4; Fails: 4; Errors: 0) 
  Firefox 3.6.25 Windows: Run 4 tests (Passed: 2; Fails: 2; Errors 0) 
    asyncTestDemo_async.testStop/start failed : AssertError: a expected 1 but was 2 
    asyncTestDemo_async.testStop/start3 failed : AssertError: a expected 2 but was 1

  Chrome 14.0.814.0 Windows: Run 4 tests (Passed: 2; Fails: 2; Errors 0) 
    asyncTestDemo_async.testStop/start failed : AssertError: a expected 1 but was 2
    asyncTestDemo_async.testStop/start3 failed : AssertError: a expected 2 but was 1


actural : in test-result.txt:
--------------------------start----------------------
Chrome: Reset
Chrome: Reset
Firefox: Reset
Firefox: Reset
F.F.F.F.
Total 8 tests (Passed: 4; Fails: 4; Errors: 0) (4034.00 ms)
  Firefox 3.6.25 Windows: Run 4 tests (Passed: 2; Fails: 2; Errors 0) (40.00 ms)
    asyncTestDemo_async.testStop/start failed (5.00 ms): AssertError: a expected 1 but was 2
      Error("a expected 1 but was 2")@:0
      equal(2,1,"a")@http://localhost:9876/test/lib/QUnitAdapter.js:160
      ()@http://localhost:9876/test/lib/QUnitAdapter.js:108
      ()@http://localhost:9876/test/lib/QUnitAdapter.js:108
      ()@http://localhost:9876/test/lib/jsUnitMockTimeout.js:47
      ()@http://localhost:9876/test/lib/jsUnitMockTimeout.js:16
      anonymous([object Object],[object Object])@http://localhost:9876/test/lib/QUnitAdapter.js:108

    asyncTestDemo_async.testStop/start3 failed (3.00 ms): AssertError: a expected 2 but was 1
      Error("a expected 2 but was 1")@:0
      equal(1,2,"a")@http://localhost:9876/test/lib/QUnitAdapter.js:160
      ()@http://localhost:9876/test/lib/QUnitAdapter.js:108
      ()@http://localhost:9876/test/lib/QUnitAdapter.js:108
      (-1,10000000)@http://localhost:9876/test/lib/jsUnitMockTimeout.js:47
      ()@http://localhost:9876/test/lib/jsUnitMockTimeout.js:57
      ()@http://localhost:9876/test/lib/jsUnitMockTimeout.js:16
      anonymous([object Object],[object Object])@http://localhost:9876/test/lib/QUnitAdapter.js:108

  Chrome 14.0.814.0 Windows: Run 4 tests (Passed: 2; Fails: 2; Errors 0) (4034.00 ms)
    asyncTestDemo_async.testStop/start failed (15.00 ms): AssertError: a expected 1 but was 2
      AssertError: a expected 1 but was 2
          at equal (http://localhost:9876/test/lib/QUnitAdapter.js:160:3)
          at [object Object].<anonymous> (eval at <anonymous> (http://localhost:9876/test/lib/QUnitAdapter.js:108:32))
          at Object.funcToCall (eval at <anonymous> (http://localhost:9876/test/lib/QUnitAdapter.js:108:32))
          at Object.runFunctionsWithinRange (http://localhost:9876/test/lib/jsUnitMockTimeout.js:47:35)

    asyncTestDemo_async.testStop/start3 failed (2003.00 ms): AssertError: a expected 2 but was 1
      AssertError: a expected 2 but was 1
          at equal (http://localhost:9876/test/lib/QUnitAdapter.js:160:3)
          at [object Object].<anonymous> (eval at <anonymous> (http://localhost:9876/test/lib/QUnitAdapter.js:108:32))
          at Object.funcToCall (eval at <anonymous> (http://localhost:9876/test/lib/QUnitAdapter.js:108:32))
          at Object.runFunctionsWithinRange (http://localhost:9876/test/lib/jsUnitMockTimeout.js:47:35)

Tests failed: Tests failed. See log for details.
--------------------end--------------------------

What version of the product are you using? On what operating system?
jsTestDriver 1.3.3d
Server : windows XP
Client  : windows XP

Please provide any additional information below.

```

Original issue reported on code.google.com by `wangj...@gmail.com` on 28 Dec 2011 at 2:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 28 Dec 2011 at 3:15
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**
