### ISSUE TITLE
Bad error message on server not started or unavailable: java.lang.RuntimeException caused by tabs in config file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#353]
```
What steps will reproduce the problem?
1. create a config file that uses tabs instead of spaces
2. run JsTestDriver.jar with any port
3. Exception is thrown (below)

What is the expected output? What do you see instead?
It would be great for it to be smarter than this, or in the least provide a 
more informative message. I found the solution here: 
http://youtrack.jetbrains.com/issue/WI-7908

Opening the jsTestDriver.conf file and changing the tabs to spaces fixes this 
problem, and the server loads as it should.

What version of the product are you using? On what operating system?
JsTestDriver-1.3.4.b.jar

Please provide any additional information below.

Here is the output:

$: java -jar JsTestDriver.jar --port 9876
setting runnermode QUIET
java.lang.RuntimeException: Connection error on: 
sun.net.www.protocol.http.HttpURLConnection:http://localhost:4224/jstd/gateway
    at com.google.jstestdriver.HttpServer.postJson(HttpServer.java:162)
    at com.google.jstestdriver.action.ConfigureGatewayAction.run(ConfigureGatewayAction.java:70)
    at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:81)
    at com.google.jstestdriver.embedded.JsTestDriverImpl.runConfigurationWithFlags(JsTestDriverImpl.java:342)
    at com.google.jstestdriver.embedded.JsTestDriverImpl.runConfiguration(JsTestDriverImpl.java:233)
    at com.google.jstestdriver.Main.main(Main.java:70)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:432)
    at java.net.Socket.connect(Socket.java:529)
    at java.net.Socket.connect(Socket.java:478)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:395)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:530)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:234)
    at sun.net.www.http.HttpClient.New(HttpClient.java:307)
    at sun.net.www.http.HttpClient.New(HttpClient.java:324)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:970)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:911)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:836)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1014)
    at com.google.jstestdriver.HttpServer.postJson(HttpServer.java:154)
    ... 5 more
Unexpected Runner Condition: Connection error on: 
sun.net.www.protocol.http.HttpURLConnection:http://localhost:4224/jstd/gateway
 Use --runnerMode DEBUG for more information.
```

Original issue reported on code.google.com by `lune...@gmail.com` on 20 Mar 2012 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
Update; Please close. I found this to be a local error on my part.

Thanks,
```

Original comment by `lune...@gmail.com` on 20 Mar 2012 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
Uhm, are you working on the eclipse plugin? If not, I have hard time figuring 
out how to go the error to bubble up.
```

Original comment by `corbinrs...@gmail.com` on 20 Mar 2012 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
Nope, was using the terminal and the basic .jar file. I was able to resolve my 
issues, which makes me think it was just a error on my part. Please close the 
ticket and sorry for the confusion!

```

Original comment by `lune...@gmail.com` on 20 Mar 2012 at 6:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 20 Mar 2012 at 7:03
- Changed title: **Bad error message on server not started or unavailable: java.lang.RuntimeException caused by tabs in config file**

**Comment by GoogleCodeExporter** [comment]
```
I am getting the same problem. What is the issue?
```

Original comment by `kyawt...@gmail.com` on 30 Mar 2012 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
I got same issue ( 
```

Original comment by `ponomare...@gmail.com` on 25 Apr 2012 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
You haven't start the server, or provided the wrong host/port.
```

Original comment by `corbinrs...@gmail.com` on 25 Apr 2012 at 2:05
