### ISSUE TITLE
Support for Intellij Idea 12 EAP Leda

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#388]
```
Please add support for Intellij Idea 12 EAP Leda.
```

Original issue reported on code.google.com by `y...@trukhin.com` on 30 Jun 2012 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
Error during dispatching of 
java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.executio
n.impl.ExecutionManagerImpl$1$1@1e1ff0f3,notifier=null,catchExceptions=false,whe
n=1341381553348] on apple.awt.CToolkit@49b35574: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V
java.lang.NoSuchMethodError: 
com.intellij.execution.testframework.sm.runner.SMTRunnerConsoleProperties.<init>
(Lcom/intellij/execution/configurations/RuntimeConfiguration;)V
    at com.google.jstestdriver.idea.TestRunnerState.execute(Unknown Source)
    at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:71)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:90)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:172)
    at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:92)
    at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:141)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:682)
    at java.awt.EventQueue.access$000(EventQueue.java:85)
    at java.awt.EventQueue$1.run(EventQueue.java:643)
    at java.awt.EventQueue$1.run(EventQueue.java:641)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:652)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:719)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:544)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

Original comment by `y...@trukhin.com` on 4 Jul 2012 at 5:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 4 Jul 2012 at 6:23

**Comment by GoogleCodeExporter** [comment]
```
Support for Idea 12 EAP will be available starting from the next EAP.
```

Original comment by `Sergey.S...@gmail.com` on 5 Jul 2012 at 11:33
- Changed state: **Accepted**
- Added labels: **IntelliJ**

**Comment by GoogleCodeExporter** [comment]
```
Cool! Thank you!
```

Original comment by `y...@trukhin.com` on 5 Jul 2012 at 11:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `Sergey.S...@gmail.com` on 21 Jul 2012 at 6:56
- Changed state: **Fixed**
