### ISSUE TITLE
Coverage throws Null Pointer Exception when decorating jQuery

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#41]
```
What steps will reproduce the problem?

* Add jquery to be loaded in jsTestDriver.conf (I'm using version 1.2.3)
* Add the coverage plugin in jsTestDriver.conf (I'm using version 1.1)
* Run JS Test Driver
* Notice the Null Pointer Exception :(

What is the expected output? What do you see instead?

I expect to see the tests run and the coverage reported.

Instead I see the following:

Warning: multiline expression on line 1 in
C:/Karl/Dev/Bonobo/src/SevenDigital.Bonobo.Web/static/lib/jquery.js has a
statement that will not be instrumented.
Warning: multiline expression on line 345 in
C:/Karl/Dev/Bonobo/src/SevenDigital.Bonobo.Web/static/lib/jquery.js has a
statement that will not be instrumented.
Warning: multiline expression on line 1354 in
C:/Karl/Dev/Bonobo/src/SevenDigital.Bonobo.Web/static/lib/jquery.js has a
statement that will not be instrumented.

Warning: multiline expression on line 1355 in
C:/Karl/Dev/Bonobo/src/SevenDigital.Bonobo.Web/static/lib/jquery.js has a
statement that will not be instrumented.

Warning: multiline expression on line 3439 in
C:/Karl/Dev/Bonobo/src/SevenDigital.Bonobo.Web/static/lib/jquery.js has a
statement that will not be instrumented.

java.lang.NullPointerException
        at com.google.jstestdriver.coverage.Statements.add(Unknown Source)
        at com.google.jstestdriver.coverage.StatementsBuilder.build(Unknown
Source)
        at
com.google.jstestdriver.coverage.CodeCoverageDecorator.decorate(Unknown Source)
        at
com.google.jstestdriver.coverage.CoverageInstrumentingProcessor.process(Unknown
Source)
        at
com.google.jstestdriver.ProcessingFileLoader.postProcessFile(Unknown Source)
        at com.google.jstestdriver.ProcessingFileLoader.loadFiles(Unknown
Source)
        at com.google.jstestdriver.CommandTask.uploadFileSet(Unknown Source)
        at com.google.jstestdriver.CommandTask.run(Unknown Source)
        at
com.google.jstestdriver.JsTestDriverClientImpl.sendCommand(Unknown Source)
        at
com.google.jstestdriver.JsTestDriverClientImpl.runAllTests(Unknown Source)
        at com.google.jstestdriver.RunTestsAction.run(Unknown Source)
        at com.google.jstestdriver.ThreadedActionRunner.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown
Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Total 0 tests (Passed: 0; Fails: 0; Errors: 0) (0.00 ms)
No lines of coverage found.

```

Original issue reported on code.google.com by `karl.oke...@gmail.com` on 1 Oct 2009 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
I also reported this in the JS Test Driver Google Group:

http://groups.google.com/group/js-test-driver/browse_thread/thread/3ce7f60544ddc
c37
```

Original comment by `karl.oke...@gmail.com` on 1 Oct 2009 at 8:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `karl.oke...@gmail.com` on 1 Oct 2009 at 9:14
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
Cory was it fixed in your latest coverage push?
```

Original comment by `toc...@gmail.com` on 21 Oct 2009 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
Yeah, I took care of this on the last push.
```

Original comment by `corbinrs...@gmail.com` on 21 Oct 2009 at 2:12
- Changed state: **Fixed**
