### ISSUE TITLE
Infinite loop after SEVERE: Error during BrowserLog write: 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#417]
```
What steps will reproduce the problem?
1. run jsTestDriver as follows:
java -jar ../JsTestDriver.jar --port 9876 --browser /usr/bin/firefox --tests 
all --testOutput results --config src-test/jsTestDriver.conf --verbose 
--runnerMode DEBUG

What is the expected output? What do you see instead?
JsTestRunner should have reported that all tests passed, instead jsTestRunner 
went into an infinite loop with the following output being repeated

com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]


What version of the product are you using? On what operating system?
- JsTestDriver-1.3.5.jar
- Ubuntu 12.04.1 LTS
- Firefox 16.0

Please provide any additional information below.

From log file:

03-Jan-2013 16:10:32 com.google.jstestdriver.CommandTask run
FINE: Finished upload for 1357258230932
03-Jan-2013 16:10:32 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:32.950Z] current command runTests
03-Jan-2013 16:10:32 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
SEVERE: Error during BrowserLog write: 
|[{"source":"log","level":2,"message":"jstestdriver.RunTestsCommand.prototype.ru
nT
ests: running tests ["all"],false,1","browser":{"id":1357258230932},"stack":"No 
stack available","timestamp":"2013-01-04T
00:10:32.953Z"}]|
com.google.gson.JsonSyntaxException: 
com.google.gson.stream.MalformedJsonException: Unterminated object near s: 
running t
ests ["all"],false,1","brows
        at com.google.gson.Streams.parse(Streams.java:51)
        at com.google.gson.Gson.fromJson(Gson.java:514)
        at com.google.gson.Gson.fromJson(Gson.java:484)
        at com.google.gson.Gson.fromJson(Gson.java:434)
        at com.google.jstestdriver.server.handlers.BrowserLoggingHandler.handleIt(BrowserLoggingHandler.java:62)
        at com.google.jstestdriver.requesthandlers.RequestDispatcher.dispatch(RequestDispatcher.java:82)
        at com.google.jstestdriver.requesthandlers.RequestHandlerServlet.service(RequestHandlerServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:389)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:879)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:747)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object 
near s: running tests ["all"],false,1","brows
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1110)
        at com.google.gson.stream.JsonReader.nextInObject(JsonReader.java:737)
        at com.google.gson.stream.JsonReader.quickPeek(JsonReader.java:379)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:332)
        at com.google.gson.Streams.parseRecursive(Streams.java:82)
        at com.google.gson.Streams.parseRecursive(Streams.java:75)
        at com.google.gson.Streams.parse(Streams.java:40)
        ... 20 more
03-Jan-2013 16:10:32 com.google.jstestdriver.CommandTask run
FINE: Starting {"command":"runTests","parameters":["[\"all\"]","false","1"]} 
for 1357258230932
03-Jan-2013 16:10:32 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:32.956Z] running configuration [object Object]
03-Jan-2013 16:10:33 com.google.jstestdriver.SlaveBrowser addResponse
FINE: adding response type TEST_RESULT done: false
Firefox 16.0 Linux [PASSED] Accordion functionality with Jasmine.should have 
contain a jasmine fixtures div
03-Jan-2013 16:10:33 com.google.jstestdriver.SlaveBrowser addResponse
FINE: adding response type TEST_RESULT done: false
Firefox 16.0 Linux [PASSED] Accordion functionality with Jasmine.should have 
contain a div
03-Jan-2013 16:10:33 com.google.jstestdriver.SlaveBrowser addResponse
FINE: adding response type TEST_RESULT done: false
03-Jan-2013 16:10:33 com.google.jstestdriver.SlaveBrowser addResponse
FINE: adding response type TEST_RESULT done: false
Firefox 16.0 Linux [PASSED] Accordion functionality with Jasmine.the div should 
contain a jquery role
Firefox 16.0 Linux [PASSED] Accordion functionality with Jasmine.should have 
section 2 open03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:33.181Z] current command streamAcknowledged

03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:33.191Z] current command streamAcknowledged
03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:33.196Z] current command streamAcknowledged
03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:33.206Z] current command streamAcknowledged
03-Jan-2013 16:10:33 com.google.jstestdriver.SlaveBrowser addResponse
FINE: adding response type TEST_RESULT done: false
Firefox 16.0 Linux [PASSED] Sinon Fake server for jqGrid.should not work with 
wrong literal
03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:33.802Z] current command streamAcknowledged
03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]
[2013-01-04T00:10:33.805Z] current command streamAcknowledged
03-Jan-2013 16:10:33 
com.google.jstestdriver.server.handlers.BrowserLoggingHandler handleIt
FINE:   [log]

```

Original issue reported on code.google.com by `mail.lis...@googlemail.com` on 4 Jan 2013 at 12:21

**Comment by GoogleCodeExporter** [comment]
```
Me too, on Mac OS X 10.8.3 with google and chrome, with:

XMLHttpRequest.w.onreadystatechange","timestamp":"2013-05-24T01:20:41.209Z"}]|
com.google.gson.JsonSyntaxException: 
com.google.gson.stream.MalformedJsonException: Unterminated object near s: 
running tests ["all"],false,1","brows
    at com.google.gson.Streams.parse(Streams.java:51)
    at com.google.gson.Gson.fromJson(Gson.java:514)
    at com.google.gson.Gson.fromJson(Gson.java:484)
    at com.google.gson.Gson.fromJson(Gson.java:434)
    at com.google.jstestdriver.server.handlers.BrowserLoggingHandler.handleIt(BrowserLoggingHandler.java:62)
    at com.google.jstestdriver.requesthandlers.RequestDispatcher.dispatch(RequestDispatcher.java:82)
    at com.google.jstestdriver.requesthandlers.RequestHandlerServlet.service(RequestHandlerServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:389)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:879)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:747)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object 
near s: running tests ["all"],false,1","brows
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1110)
    at com.google.gson.stream.JsonReader.nextInObject(JsonReader.java:737)
    at com.google.gson.stream.JsonReader.quickPeek(JsonReader.java:379)
    at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:332)
    at com.google.gson.Streams.parseRecursive(Streams.java:82)
    at com.google.gson.Streams.parseRecursive(Streams.java:75)
    at com.google.gson.Streams.parse(Streams.java:40)
    ... 20 more
```

Original comment by `Andy.Co...@gmail.com` on 24 May 2013 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
I meant Chrome and Firefox, latest available...

```

Original comment by `Andy.Co...@gmail.com` on 24 May 2013 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
Me too, on Windows 7 x64 with Internet Explorer 9.
```

Original comment by `zippanova@gmail.com` on 20 Jun 2013 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem too. Since I tried to use AsyncTestCase.
```

Original comment by `dipdipdi...@gmail.com` on 2 Jul 2013 at 12:56
