### ISSUE TITLE
Occasionally getting java.lang.RuntimeException: Test run cancelled, exceeded 7200s

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#420]
```
I haven't figured out how to reproduce this, but this is the scenario:
1.Tests are under a ContinuousBuild (Jenkins v1.491) environment running on a 
linux OS
2.Test runner and browsers are on a virtual machine running Windows7
3.Sometimes I get this exception: java.lang.RuntimeException: Test run 
cancelled, exceeded 7200s

I'm not sure if this is a bug. I just don't understand what causes this 
exception.

Version:
JsTestDriver-1.3.2

Full log:
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Chrome: {}
Failures during test run.
Caused by:
java.lang.RuntimeException: Test run cancelled, exceeded 7200s
        at com.google.jstestdriver.browser.BrowserActionExecutorAction.run(BrowserActionExecutorAction.java:126)
        at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
        at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:86)
Caused by: java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:220)
        at java.util.concurrent.FutureTask.get(FutureTask.java:83)
        at com.google.jstestdriver.browser.BrowserActionExecutorAction.run(BrowserActionExecutorAction.java:122)
        ... 2 more

        at com.google.jstestdriver.browser.BrowserActionExecutorAction.run(BrowserActionExecutorAction.java:142)
        at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:64)
        at com.google.jstestdriver.JsTestDriver.main(JsTestDriver.java:86)
Caused by:
java.lang.RuntimeException: Test run cancelled, exceeded 7200s
Unexpected Runner Condition: Failures during test run.
 Use --runnerMode DEBUG for more information.
```

Original issue reported on code.google.com by `mail.rol...@gmail.com` on 31 Jan 2013 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue as well but for me it always happen and 
jsTestDriver.conf-coverage.dat is of size 0.

Thanks
```

Original comment by `g...@tikalk.com` on 17 Sep 2013 at 6:07
