### ISSUE TITLE
NPE on instrumentation.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#50]
```
What steps will reproduce the problem?
1. Had a working version of JSTestDriver and code. Copied the coverage jar 
file to plugins directory and included the following in the conf file:

plugin:
- name: "coverage"
  jar: "plugins/coverage-1.1a.jar"
  module: "com.google.jstestdriver.coverage.CoverageModule"

2. Run JsTestDriver using the following command after successfully 
capturing a browser:

java -jar jstestdriver-1.1.jar --tests all --testOutput c:\jstestdriver

3. Exception occurred.

What is the expected output? What do you see instead?
Expected to see test coverage report in directory; but got the following 
exception instead:

NoClassDefFoundError: com/google/jstestdriver/hooks/ActionListProcessor

What version of the product are you using? On what operating system?
JsTestDriver 1.1
Coverage 1.1a
IE 6

Please provide any additional information below.
I checked JsTestDriver.jar and could not find the class that it was 
looking for (ActionListProcessor).

```

Original issue reported on code.google.com by `lighteni...@gmail.com` on 19 Oct 2009 at 4:28
- Merged into: #210

**Comment by GoogleCodeExporter** [comment]
```
Hi, even i'm facing the same problem.

     [exec] java.lang.NullPointerException
     [exec]  at java.lang.Class.forName0(Native Method)
     [exec]  at java.lang.Class.forName(Unknown Source)
     [exec]  at com.google.jstestdriver.PluginLoader.load(Unknown Source)
     [exec]  at com.google.jstestdriver.JsTestDriverServer.main(Unknown Source)
```

Original comment by `Ravi.Pas...@gmail.com` on 19 Oct 2009 at 7:21

**Comment by GoogleCodeExporter** [comment]
```
Ravi:

Your's is a NullPointerException, which is different to what I got.  What did 
you do 
to get the NullPointerException?
```

Original comment by `lighteni...@gmail.com` on 20 Oct 2009 at 4:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `toc...@gmail.com` on 21 Oct 2009 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
We've re-released JsTestDriver and the coverage plugin. Does it fix things for 
you?
```

Original comment by `toc...@gmail.com` on 2 Nov 2009 at 7:19

**Comment by GoogleCodeExporter** [comment]
```
I have just installed coverage1.2.jar and JsTestDriver1.2.jar.  Now I got a new 
null 
pointer exception.  It appears that there is some sort of tokenising problems 
right 
at the first character of the first line of code in my javascript file:

line 0:0 no viable alternative at character ' '
line 0:0 no viable alternative at character ' '
line 13:0 no viable alternative at input 'function'
java.lang.NullPointerException
        at com.google.jstestdriver.coverage.es3.ES3InstrumentParser.statement
(Unknown Source)
        at com.google.jstestdriver.coverage.es3.ES3InstrumentParser.sourceElement
(Unknown Source)
        at com.google.jstestdriver.coverage.es3.ES3InstrumentParser.program(Unknown 
Source)
        at com.google.jstestdriver.coverage.CodeCoverageDecorator.decorate(Unknown 
Source)
        at com.google.jstestdriver.coverage.CoverageInstrumentingProcessor.process
(Unknown Source)
        at com.google.jstestdriver.ProcessingFileLoader.postProcessFile
(UnknownSource)
        at com.google.jstestdriver.ProcessingFileLoader.loadFiles(Unknown Source)
        at com.google.jstestdriver.CommandTask.uploadFileSet(Unknown Source)
        at com.google.jstestdriver.CommandTask.run(Unknown Source)
        at com.google.jstestdriver.JsTestDriverClientImpl.sendCommand(Unknown Source)
        at com.google.jstestdriver.JsTestDriverClientImpl.runAllTests(Unknown Source)
        at com.google.jstestdriver.RunTestsAction.run(Unknown Source)
        at com.google.jstestdriver.ThreadedActionRunner.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask
(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run
(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)
Total 0 tests (Passed: 0; Fails: 0; Errors: 0) (0.00 ms)
Nov 4, 2009 2:41:06 PM com.google.jstestdriver.BrowserShutdownAction run
WARNING: Unexpected shutdown java.lang.ProcessImpl@39060b 1
No lines of coverage found.


```

Original comment by `lighteni...@gmail.com` on 4 Nov 2009 at 3:47

**Comment by GoogleCodeExporter** [comment]
```
Can you provide the code that caused the tokenizing error?
I'll look into giving a better error message.
```

Original comment by `corbinrs...@gmail.com` on 4 Nov 2009 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
This is all I can provide for now.  The error happens right at the beginning of 
the 
file.

Thanks.

```

Original comment by `lighteni...@gmail.com` on 4 Nov 2009 at 6:25

Attachments:
- [codeSnipet.js](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-50/comment-7/codeSnipet.js)

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 5 Nov 2009 at 1:32
- Changed title: **NPE on instrumentation.**

**Comment by GoogleCodeExporter** [comment]
```
So, I'm not having this issue on head. The code instruments fine. If you can 
isolate
the code snippet that actually causes the NPE, please attach it.

/**
 *
 * This file depends on JQuery
 *
 * Note: The vast majority of method names and AJAX calls are tokensed
 **/

/***********************************************************************
 * This Section FIXES a sync problem with ASP callbacks
 **********************************************************************/
LCOV_crtdry=LCOV.initNoop('/repos/js-test-driver/JsTestDriver/src-test/com/googl
e/jstestdriver/coverage/javascript/Instrumentable.js',0,[11,
12, 13, 14, 15, 16, 18, 19, 20, 22, 23, 25, 30, 31, 33, 37, 42, 45, 47,
51]);LCOV_crtdry[11]++; function WebForm_CallbackComplete_SyncFixed() {
     LCOV_crtdry[12]++; for (var i = 0; i < __pendingCallbacks.length; i++) {
        LCOV_crtdry[13]++; callbackObject = __pendingCallbacks[ i ];
        LCOV_crtdry[14]++; if (callbackObject && callbackObject.xmlRequest &&
(callbackObject.xmlRequest.readyState == 4)) {
            LCOV_crtdry[15]++; if (!__pendingCallbacks[ i ].async) {
                LCOV_crtdry[16]++; __synchronousCallBackIndex = -1;
            }
            LCOV_crtdry[18]++; __pendingCallbacks[i] = null;
            LCOV_crtdry[19]++; var callbackFrameID = "__CALLBACKFRAME" + i;
            LCOV_crtdry[20]++; var xmlRequestFrame =
document.getElementById(callbackFrameID);

            LCOV_crtdry[22]++; if (xmlRequestFrame) {
                LCOV_crtdry[23]++;
xmlRequestFrame.parentNode.removeChild(xmlRequestFrame);
            }
            LCOV_crtdry[25]++; executeCallback(callbackObject);
        }
    }
}

LCOV_crtdry[30]++; $(document).ready(function() {
    LCOV_crtdry[31]++; if (typeof (callbackComplete) == "function") {
      // set the original version with fixed version
      LCOV_crtdry[33]++; callbackComplete = callbackComplete_SyncFixed;
    }
});

 LCOV_crtdry[37]++; var ID = "idTreeView";

 /**
 * Checks to see if the tree view actually exists on the page
 **/
LCOV_crtdry[42]++; function doesTreeViewExist()
{

    LCOV_crtdry[45]++; if($('#' + ID).length == 0)
    {
        LCOV_crtdry[47]++; return false;
    }
    else
    {
    LCOV_crtdry[51]++; return true;
    }
}

```

Original comment by `corbinrs...@gmail.com` on 5 Nov 2009 at 2:40

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Thats strange.  I used the same test file and code, and I still got the same 
NPE.  
Below is the plugin setting from my conf file:

server: http://localhost:4225

load:
- qunit.js
- jquery-1.3.2.min.js
- jack.js
- testCode.js
- testSource.js

plugin:
- name: "coverage"
  jar: "plugins/coverage-1.2.jar"
  module: "com.google.jstestdriver.coverage.CoverageModule"


I have tried commenting out the other js files i.e. qunit.js, 
jquery-1.3.2.min.js 
(that one caused a no viable alternative at input 'if' at line 12:9095) and 
jack.js, 
but still ended up with the same NPE.

This is the command I use in the command line:

java -jar jstestdriver-1.2.jar --port 4225 --browser "c:\program files\internet 
explorer\iexplore.exe" --tests all --testOutput c:\jstestdriver

On a side note: I'm yet to figure out how not to make the browser to pop up 
when I 
run that command on the CI server.

```

Original comment by `lighteni...@gmail.com` on 5 Nov 2009 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
I have given the test coverage tool many tries.  It just refused to work and 
returned me the same NPE.  I have included the entire code/test code which 
caused 
the error along with the stacktrace in a zip file.  Could you please try it and 
see 
if you can produce the same problem?

Thanks.

```

Original comment by `lighteni...@gmail.com` on 17 Nov 2009 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
I have just tried a very simple code and setup, with 1 function returning true 
or 
false and 2 tests for it.  Tried running coverage on it, but it still returns 
the 
same NPE complaining line 0:0- no viable alternative at character ' ' and line 
1:4 
no viable alternative at input 'var' (or whatever the first word in the 
javascript 
file is).

Am I missing something, or do I have to put the files into certain directories, 
or 
did I name something wrong??

```

Original comment by `lighteni...@gmail.com` on 19 Nov 2009 at 2:55

**Comment by GoogleCodeExporter** [comment]
```
Update: issue resolved. Turns out that JsTestCoverage does not like files that 
are 
encoded in Unicode.  I saved the files in ANSI format, and the "Line 0:0 no 
viable 
character at ' ' " error disappeared.
```

Original comment by `lighteni...@gmail.com` on 5 Jan 2010 at 12:50

**Comment by GoogleCodeExporter** [comment]
```
Any news on this issue? changing to ANSI format is not a solution for me. 
Please, Unicode should be accepted, as the rest of js-test-driver does.
Kind Regards,
```

Original comment by `benja1...@gmail.com` on 4 Dec 2010 at 11:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 14 Feb 2011 at 4:40
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
1.3.1 Explicitly reads file using Charset.defaultCharset(). Please see if this 
resolves the issue.
```

Original comment by `corbinrs...@gmail.com` on 18 Feb 2011 at 5:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 30 Mar 2011 at 10:58
- Changed state: **Duplicate**
