### ISSUE TITLE
IDEA plugin: Socket connect exception streaming results back to IDE process

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#58]
```
Exception in thread "main" java.net.SocketException: Socket closed
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at
java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:310)
    at
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:1
76)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:163)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:381)
    at java.net.Socket.connect(Socket.java:537)
    at com.google.jstestdriver.idea.TestRunner.main(TestRunner.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:90)
```

Original issue reported on code.google.com by `aeagle22206` on 27 Oct 2009 at 2:11

**Comment by GoogleCodeExporter** [comment]
```
Fixed on head
http://code.google.com/p/js-test-driver/source/detail?r=428
```

Original comment by `aeagle22206` on 27 Oct 2009 at 2:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 27 Oct 2009 at 2:39
- Changed state: **Fixed**
