### ISSUE TITLE
Globing using ** in jsTestDriver.conf throws NullReferenceException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#6]
```
What steps will reproduce the problem?
1. In jsTestDriver.conf add a load path containing two asterix eg src/**/*.js 
2. Run all tests

What is the expected output? What do you see instead?
Normal execution of the test driver but a NullReferenceException is thrown

What version of the product are you using? On what operating system?
1.0b on Windows 7 Beta



```

Original issue reported on code.google.com by `persson....@gmail.com` on 31 May 2009 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
We do not support ** for now, I guess we should print a friendlier message 
though... 

Do you know a java library that would resolve those correctly? I think ant 
might have
something like this. I need to look into it see if we can reuse it.
```

Original comment by `toc...@gmail.com` on 2 Jun 2009 at 11:31
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I could just have checked the code if it was a feature first.

I don't know of any libraries unfortunatly since I mostly do .NET development. 
I know
Ant have the wildcards I described
(http://ant.apache.org/manual/dirtasks.html#patterns) perhaps something could be
reused from that codebase?



```

Original comment by `persson....@gmail.com` on 4 Jun 2009 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
This appears to happen with just a single * as well. Windows XP, 1.0b.
```

Original comment by `jani.hartikainen` on 31 Aug 2009 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
I'd love to see globing support as well.  Using '**' in our config file would 
greatly simplify it.
```

Original comment by `burke.we...@gmail.com` on 25 Sep 2009 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
I'm working on this, and would like to submit it to the project if it hasn't 
already
been implemented.
```

Original comment by `burke.we...@gmail.com` on 30 Sep 2009 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
Hi Burke,

if you have a patch that works please feel free to submit it.

Thanks !
```

Original comment by `toc...@gmail.com` on 2 Nov 2009 at 6:48

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The attached patch will add glob support.  I've done some initial testing and it
seems to work well.  I also moved the error handling down a bit so that it will
collect all errors while parsing the config file, and print them out at the end
(instead of failing after the first invalid entry).

Burke
```

Original comment by `burke.we...@gmail.com` on 5 Nov 2009 at 6:02

Attachments:
- [Globbing_support_for_config_file_entries.patch](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-8/Globbing_support_for_config_file_entries.patch)

**Comment by GoogleCodeExporter** [comment]
```
I did not see Burke's patch before implementing my own version of "**" 
globbing.  Burke's implementation is probabyl better, but in case anyone is 
interested a patch for my implementation is attached.
```

Original comment by `halle...@gmail.com` on 9 Jul 2010 at 10:54

Attachments:
- [Support-for-recursive-file-globs-of-the-form-test-un.patch](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-9/Support-for-recursive-file-globs-of-the-form-test-un.patch)

**Comment by GoogleCodeExporter** [comment]
```
Are this fix present in any version of jsTestDriver?
```

Original comment by `chrak...@gmail.com` on 21 Oct 2010 at 11:22

**Comment by GoogleCodeExporter** [comment]
```
It is definitely not in the latest version, as I am not able to  execute tests 
with globing paths ... I would also like this feature without having to patch 
every time new version is released?


Ex.
Testing started at 10:58 AM ...
The patterns/paths lib/**/*.js used in the configuration file didn't match any 
file, the files patterns/paths need to be relative to the configuration file.
Exception in thread "main" java.lang.RuntimeException: The patterns/paths 
lib/**/*.js used in the configuration file didn't match any file, the files 
patterns/paths need to be relative to the configuration file.
    at com.google.jstestdriver.ConfigurationParser.resolveFiles(ConfigurationParser.java:150)
    at com.google.jstestdriver.ConfigurationParser.parse(ConfigurationParser.java:69)
    at com.google.jstestdriver.idea.TestRunner.parsePluginsFromConfFile(Unknown Source)
    at com.google.jstestdriver.idea.TestRunner.makeActionBuilder(Unknown Source)
    at com.google.jstestdriver.idea.TestRunner.execute(Unknown Source)
    at com.google.jstestdriver.idea.TestRunner.main(Unknown Source)
Empty test suite.
```

Original comment by `ireney.b...@gmail.com` on 18 Nov 2010 at 5:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 13 Dec 2010 at 3:42
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I've just tried using 'lib/**/*.js' style matching with js-test-driver version 
1.3.1, and this patch still doesn't seem to have been integrated. Is this 
correct, and/or are there any plans to integrate this patch?
```

Original comment by `dominic....@gmail.com` on 28 Feb 2011 at 10:58

**Comment by GoogleCodeExporter** [comment]
```
It's not my highest priority, and adding the apache io commons is going to be a 
pain. :P

So, yes, eventually. Just not for the 1.3.2 release.
```

Original comment by `corbinrs...@gmail.com` on 28 Feb 2011 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
So at this point, without the global wildcard, what is the preferred method of 
listing folders in the config file?  Should we add each new folder in the 
hierarchy to the config file?
```

Original comment by `chris.ru...@gmail.com` on 29 Mar 2011 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
This is definitely needed, as it somewhat hinders the use of JsTestDriver in 
bigger projects, or even with libraries like Google Closure.
```

Original comment by `mikko.ti...@gmail.com` on 30 Mar 2011 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
I agree, this is really a MUST in my book.  We just started using this on a 
large project and I really don't want to have to put in every single directory 
that contains scripts.  I shouldn't have to add every directory that contains 
scripts, otherwise it is VERY likely that these tests will never get run and 
likely not even noticed.

I think this should really be a high priority issue as it effects the 
usefulness of this library in a large scale project.
```

Original comment by `warchild...@gmail.com` on 31 Mar 2011 at 4:55

**Comment by GoogleCodeExporter** [comment]
```
So, I do intend to fix this. However, there is one small misconception I need 
to address: we use JsTD at Google. For Closure tests. 

How you might ask? Very simply: we generate the configuration files from our 
internal build system.

So, I understand that you have a use case that requires attention, but it's 
mis-characterizing the issue to say that it limits the use of JsTD on large 
scale projects.
```

Original comment by `corbinrs...@gmail.com` on 31 Mar 2011 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
I don't believe it is mis-characterizing due to the fact that the tool does not 
follow a convention that is standard for globbing.  I also understand that it 
can be used by large projects, but it does require extra work (we have to write 
our own scripts to handle automated config file generation).  It should be too 
difficult to do, it just is a pain.
```

Original comment by `warchild...@gmail.com` on 31 Mar 2011 at 11:19

**Comment by GoogleCodeExporter** [comment]
```
I'd agree that while this issue is an inconvenience, it's not a show-stopper.  
We are using this testing framework on a large javascript codebase and have 
gone the route of generating the config file via maven.  It's worked well for 
us so far.
```

Original comment by `burke.we...@gmail.com` on 1 Apr 2011 at 12:14

**Comment by GoogleCodeExporter** [comment]
```
Vote that this feature is very important and will prevent lot of headaches in 
small and big projects
```

Original comment by `vmykhai...@intelliarts.net` on 5 Jul 2011 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
This is a mandatory feature if you want make anything beyond a toy project. 
Depending on generated configs is a show stopper.
```

Original comment by `lars.ro...@gmail.com` on 23 Jul 2011 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
Does anybody have a patch for ** globing support against the current trunk? 
Thanks!

```

Original comment by `mistae...@gmail.com` on 17 Sep 2011 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
^Bump^, we'd love a patch for an up to date js-test-driver that does this too. 
Can anyone help?


```

Original comment by `dominic....@gmail.com` on 20 Sep 2011 at 9:44

**Comment by GoogleCodeExporter** [comment]
```
This feature is really needed.
```

Original comment by `enwukaer@gmail.com` on 26 Oct 2011 at 4:05

**Comment by GoogleCodeExporter** [comment]
```
Hello Burke,

I cannot get patch up and working on latest version of jstestdriver. 
If you have patched version already, can you please upload it.

Thanks
Nish
```

Original comment by `nisheeth...@gmail.com` on 24 Jan 2012 at 4:23

**Comment by GoogleCodeExporter** [comment]
```
Here's a more recent patch (against 1.3.3d) providing deep globbing support, 
and some unit tests too

```

Original comment by `dominic....@gmail.com` on 21 Mar 2012 at 5:21

Attachments:
- [PathResolver.diff](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-27/PathResolver.diff)
- [PathResolverTest.diff](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-27/PathResolverTest.diff)

**Comment by GoogleCodeExporter** [comment]
```
Uploading a new patch against HEAD. Any chance this can be integrated while 
it's still fresh?

```

Original comment by `dominic....@gmail.com` on 31 Mar 2012 at 9:01

Attachments:
- [PathResolver.patch](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-28/PathResolver.patch)
- [PathResolverTest.patch](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-28/PathResolverTest.patch)

**Comment by GoogleCodeExporter** [comment]
```
Oh, it's probably worth pointing out that my patch uses this syntax:

  src/**.js 

rather than this syntax:

  src/**/*.js

But it does mean that the patch is tiny (a single new method), and I personally 
don't think the Ant syntax is better anyway.

```

Original comment by `dominic....@gmail.com` on 31 Mar 2012 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
Better or not, it should conform to the standards. And the standard is "**/*". 
Not only in Ant. This syntax is older than Java.
```

Original comment by `enwukaer@gmail.com` on 31 Mar 2012 at 3:26

**Comment by GoogleCodeExporter** [comment]
```
Uploading a diff (against 1.3.4b release) adding deep directory globbing 
support with **/* syntax.

Any chance this can be integrated into the codebase?

```

Original comment by `AndyBerr...@gmail.com` on 19 Apr 2012 at 2:39

Attachments:
- [PathResolver.java](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-31/PathResolver.java)
- [PathResolverTest.java](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-31/PathResolverTest.java)
- [PathResolver.java.diff](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-31/PathResolver.java.diff)
- [PathResolverTest.java.diff](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-6/comment-31/PathResolverTest.java.diff)

**Comment by GoogleCodeExporter** [comment]
```
The apache ORO makes it difficult to apply the patch, unfortunately. It 
translates to extra maintenance burden at work.
```

Original comment by `corbinrs...@gmail.com` on 19 Apr 2012 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
I've not made any more use of ORO than what was already there. There is only 
one extra method.

The current head revision 
(https://js-test-driver.googlecode.com/svn/trunk/JsTestDriver/src/com/google/jst
estdriver/PathResolver.java) already uses both 
org.apache.oro.io.GlobFilenameFilter and org.apache.oro.text.GlobCompiler.
```

Original comment by `AndyBerr...@gmail.com` on 19 Apr 2012 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
Ack. Too many patches... it was an earlier other Apache project in a patch. 
Yeah, this one I can integrate. 

Just need an ICLA, as I don't think I have one from you: 
http://code.google.com/legal/individual-cla-v1.0.html
```

Original comment by `corbinrs...@gmail.com` on 19 Apr 2012 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
Done.
```

Original comment by `AndyBerr...@gmail.com` on 19 Apr 2012 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
Thanks. Will integrate shortly.
```

Original comment by `corbinrs...@gmail.com` on 19 Apr 2012 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
Hi, how can I get a build with the PathResolver?  trying to build off of trunk, 
but does not seem to be integrated.  Also hard to tell from here, did you got 
with the patch version to use **.js, or the standard /**/*.js?  Thanks for any 
help, anxious awaiting this change.
```

Original comment by `dfitzhe...@gmail.com` on 23 Apr 2012 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
I integrated Andy's patch and it worked great for me.  Until the patch is 
integrated officially, this might be helpful to others: 
https://github.com/davidjnelson/js-test-driver-recursive-glob for the source, 
and http://dl.dropbox.com/u/4208692/JsTestDriver.jar for the binary.
```

Original comment by `david.jonathan.nelson` on 26 Apr 2012 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
Thank you David for providing a binary.
```

Original comment by `bret.lit...@gmail.com` on 9 May 2012 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
Patched to trunk in 
https://code.google.com/p/js-test-driver/source/detail?r=e8949ae10a46231474ffa57
f8d1dc923fcfe1b61

Next release will have it (tentative for June 16th, 2012)
```

Original comment by `corbinrs...@gmail.com` on 6 Jun 2012 at 11:23
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi, which version is this due to go out in, is there an ETA?

thanks!
```

Original comment by `monkeybo...@gmail.com` on 12 Sep 2012 at 1:56
