### ISSUE TITLE
IntelliJ plugin not working in version 9 of IntelliJ platform (IDEA, PHPStorm, RubyMine, WebStorm)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#82]
```
What steps will reproduce the problem?
1. setup config file
2. setup runner within intellij
3. start jstestdriver server
4. run tests

What is the expected output? What do you see instead?
Expect to see output of results

Internal IDE error:
Error during dispatching of
java.awt.event.MouseEvent[MOUSE_RELEASED,(475,62),absolute(471,58),button=1,modi
fiers=Button1,clickCount=1]
on frame0:
com.intellij.execution.testframework.sm.runner.ui.SMTestRunnerResultsForm.<init>
(Lcom/intellij/execution/configurations/RunConfigurationBase;Lcom/intellij/execu
tion/testframework/TestConsoleProperties;Lcom/intellij/execution/configurations/
RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSett
ings;)V
java.lang.NoSuchMethodError:
com.intellij.execution.testframework.sm.runner.ui.SMTestRunnerResultsForm.<init>
(Lcom/intellij/execution/configurations/RunConfigurationBase;Lcom/intellij/execu
tion/testframework/TestConsoleProperties;Lcom/intellij/execution/configurations/
RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSett
ings;)V
    at com.google.jstestdriver.idea.TestRunnerState.execute(Unknown Source)
    at
com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgra
mRunner.java:87)
    at
com.intellij.execution.runners.GenericProgramRunner$1.run(GenericProgramRunner.j
ava:95)
    at
com.intellij.execution.impl.ExecutionManagerImpl$1.run(ExecutionManagerImpl.java
:124)
    at
com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerI
mpl.java:133)
    at
com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner
.java:119)
    at
com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner
.java:70)
    at
com.intellij.execution.ExecutionUtil.executeConfiguration(ExecutionUtil.java:82)
    at
com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.actionPerformed(Execu
torRegistryImpl.java:193)
    at
com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:146)
    at
com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:122)
    at
com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButt
on.java:282)
    at java.awt.Component.processEvent(Component.java:6028)
    at java.awt.Container.processEvent(Container.java:2041)
    at java.awt.Component.dispatchEventImpl(Component.java:4630)
    at java.awt.Container.dispatchEventImpl(Container.java:2099)
    at java.awt.Component.dispatchEvent(Component.java:4460)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4574)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
    at java.awt.Container.dispatchEventImpl(Container.java:2085)
    at java.awt.Window.dispatchEventImpl(Window.java:2475)
    at java.awt.Component.dispatchEvent(Component.java:4460)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:621)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:507)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:372)
    at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269
)
    at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174
)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)


What version of the product are you using? On what operating system?
v1.2 of plugin
v9.0 of intellij

Please provide any additional information below.

```

Original issue reported on code.google.com by `travi...@gmail.com` on 18 Dec 2009 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
We just upgraded to IntelliJ 9 and have hit the same problem.  This is a pretty 
big issue for us.  We used the 
plug-in in IntelliJ 8 all the time.
```

Original comment by `burke.we...@gmail.com` on 7 Apr 2010 at 6:07

**Comment by GoogleCodeExporter** [comment]
```
This is a big issue for us. Please address as soon as possible. Thank you!
```

Original comment by `jacwri...@gmail.com` on 19 May 2010 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
We don't have a maintainer for the Intelli-J plugin.

If it's a big issue, please consider contributing the fix.
```

Original comment by `corbinrs...@gmail.com` on 19 May 2010 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Fair enough.  I'll take a look at the code and see if I can make sense of how 
to update it.
```

Original comment by `burke.we...@gmail.com` on 19 May 2010 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
Issue 134 has been merged into this issue.
```

Original comment by `aeagle22206` on 14 Sep 2010 at 6:56

**Comment by GoogleCodeExporter** [comment]
```
Issue 96 has been merged into this issue.
```

Original comment by `aeagle22206` on 14 Sep 2010 at 6:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 14 Sep 2010 at 6:58
- Changed title: **IntelliJ plugin not working in version 9 of IntelliJ platform (IDEA, PHPStorm, RubyMine, WebIDE)**
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 14 Sep 2010 at 10:51
- Changed title: **IntelliJ plugin not working in version 9 of IntelliJ platform (IDEA, PHPStorm, RubyMine, WebStorm)**

**Comment by GoogleCodeExporter** [comment]
```
Alexey from IntelliJ confirms that the remaining problem with non-IDEA 
"platform" products is on their side:

Well, I've added the missing "default runner" to platform, so the "Run" action 
is now enabled in PS, WS and other IDEs. It will be available in since next PS 
EAP build (I think I will be able to publish it in next couple of days).

I'm going to push a release of the plugin now, so that IDEA9 users can start 
using it. Hopefully it will also work with the next release of the platform 
IDEs.
```

Original comment by `alexea...@google.com` on 17 Sep 2010 at 6:57

**Comment by GoogleCodeExporter** [comment]
```
Where can I download the new plugin? It is not available from within IDEA.
```

Original comment by `timomeinen` on 24 Sep 2010 at 4:15

**Comment by GoogleCodeExporter** [comment]
```
I needed to restrict the versioning, since it's not compatible with the current 
release of {Web,Php}Storm, RubyMine, etc.

I went with since-build="IC-93.13". It's not clear that this also works with 
IDEA Ultimate, but I hope it will. In any case, I'll have to make more API 
changes soon to work with the new EAP of the other IDEs.

Just uploaded to the Jetbrains plugin repo, it should be available any minute.
```

Original comment by `alexea...@google.com` on 24 Sep 2010 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
Thank you very much. For me, it's working now in IDEA 9.0.3 Ultimate.
```

Original comment by `timomeinen` on 26 Sep 2010 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
Get version 1.2.2a at http://plugins.intellij.net/plugin/?id=4468

Notice the comment about the IDE version - you need an "EAP" release at build 
96.1224 or higher, to get a bugfix from JetBrains which enables the run button.
```

Original comment by `aeagle22206` on 13 Oct 2010 at 4:30
- Changed state: **Fixed**
