### ISSUE TITLE
windows 7 not working..?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#84]
```
What steps will reproduce the problem?
java -jar JsTestDriver-1.2.jar  --port 9876 --browser \"c:/Program
Files/Mozilla Firefox/firefox.exe\"



What is the expected output? What do you see instead?
capture the browser like in Linux, but I see a bunch of errors.  



"Dec 23, 2009 7:33:08 AM org.mortbay.log.Slf4jLog info
INFO: Logging to org.slf4j.impl.JDK14LoggerAdapter(org.mortbay.log) via
org.mortbay.log.Slf4jLog
Dec 23, 2009 7:33:08 AM org.mortbay.log.Slf4jLog info
INFO: jetty-6.1.x
Dec 23, 2009 7:33:08 AM org.mortbay.log.Slf4jLog warn
WARNING: failed SocketConnector@0.0.0.0:9876
java.net.SocketException: Unrecognized Windows Sockets error: 0: JVM_Bind
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.PlainSocketImpl.bind(Unknown Source)
    at java.net.ServerSocket.bind(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at
org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
    at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
    at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
    at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.Server.doStart(Server.java:235)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.google.jstestdriver.JsTestDriverServer.start(Unknown Source)
    at com.google.jstestdriver.ServerStartupAction.run(Unknown Source)
    at com.google.jstestdriver.ActionRunner.runActions(Unknown Source)
    at com.google.jstestdriver.JsTestDriverServer.main(Unknown Source)
Dec 23, 2009 7:33:08 AM org.mortbay.log.Slf4jLog warn
WARNING: failed Server@5973ea
java.net.SocketException: Unrecognized Windows Sockets error: 0: JVM_Bind
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.PlainSocketImpl.bind(Unknown Source)
    at java.net.ServerSocket.bind(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at
org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
    at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
    at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
    at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.Server.doStart(Server.java:235)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.google.jstestdriver.JsTestDriverServer.start(Unknown Source)
    at com.google.jstestdriver.ServerStartupAction.run(Unknown Source)
    at com.google.jstestdriver.ActionRunner.runActions(Unknown Source)
    at com.google.jstestdriver.JsTestDriverServer.main(Unknown Source)
java.lang.RuntimeException: java.net.SocketException: Unrecognized Windows
Sockets error: 0: JVM_Bind
    at com.google.jstestdriver.JsTestDriverServer.start(Unknown Source)
    at com.google.jstestdriver.ServerStartupAction.run(Unknown Source)
    at com.google.jstestdriver.ActionRunner.runActions(Unknown Source)
    at com.google.jstestdriver.JsTestDriverServer.main(Unknown Source)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0:
JVM_Bind
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.PlainSocketImpl.bind(Unknown Source)
    at java.net.ServerSocket.bind(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at
org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
    at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
    at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
    at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.Server.doStart(Server.java:235)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)







What version of the product are you using? On what operating system?
Windows 7




Maybe it's the user privilege security thingy that windows 7 has?  Maybe
it's the firewall?  I don't know..  But it's not important, I can play in
my linux box.
```

Original issue reported on code.google.com by `ohapp...@gmail.com` on 23 Dec 2009 at 2:13

**Comment by GoogleCodeExporter** [comment]
```
It works in windows 7.  It got this error because I started a process running 
the
server in the background.  Of course the "ps aux | grep" didn't work in Windows 
and I
didn't know the process has already started and tried to start it again.

Basically, it works in windows 7.  The error is there because the js-testdriver
server is already running.
```

Original comment by `ohapp...@gmail.com` on 24 Dec 2009 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
Okay, closing this issue.
```

Original comment by `corbinrs...@gmail.com` on 10 Jan 2010 at 9:31
- Changed state: **Invalid**
