### ISSUE TITLE
Guice provision error when automating JsTestDriver and JsCoverage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#91]
```
What steps will reproduce the problem?
1.Setup JsTestDriver and JsTestCoverage.
2.Integrate them into an automated build environment (1 line command to 
automate unit testing).
3.Execute the tests.

What is the expected output? What do you see instead?
Expected test to run properly and coverage report generated in proper 
directory. However, got the following error instead (no other outputs from 
JsTestDriver):

------------------------------------------------------------------
com.google.inject.ProvisionException: Guice provision errors:

1) Error in custom provider, java.lang.RuntimeException: 
java.lang.reflect.InvocationTargetEception
    at 
com.google.jstestdriver.coverage.CoverageModule.createCoverageWriter
(Unknown Source)
    while locating com.google.jstestdriver.coverage.CoverageWriter 
for parameter 1 at 
com.google.jstestdriver.coverage.CoverageActionDecorator. <init>(Unknown 
Source)
    while locating 
com.google.jstestdriver.coverage.CoverageActionDecorator
    while locating com.google.jstestdriver.hooks.ActionListProcessor 
annotated with @com.google.inject.multibindings.Element
(setName=,UniqueId=5)
    at com.google.jstestdriver.ActionFactoryModule.configure(Unknown 
Source)
    while locating 
java.util.Set<com.google.jstestdriver.hooks.ACtionListProcessor>
    for parameter 17 at 
com.google.jstestdriver.ActionRunner.<init><Unknown Source)
    while locating com.google.jstestdriver.ActionRunner
    1 error

    at com.google.inject.InjectorImpl$4.get(InjectorImpl.java:767)
    at com.google.inject.InjectorImpl.getInstance
(InjectorImpl.java:793)
    at com.google.jstestdriver.JsTestDriverServer.main(Unknown Source)

    Caused by: java.lang.RuntimeException: 
java.lang.reflect.InvocationTargetException
    at com.google.inject.internal.ProviderMethod.get
(ProviderMethod.java:106)
    at com.google.inject.InternalFactoryToProviderAdapter.get
(InternalFactoryToProviderAdapter.java:48)
    at com.google.inject.SingleParameterInjector.inject
(SingleParameterInjector.java:42)
    at com.google.inject.SingleParameterInjector.getAll
(SingleParameterInjector.java:66)
    at com.google.inject.ConstructorInjector.construct
(ConstructorInjector.java:84)
    at com.google.inject.ConstructorBindingImpl$Factory.get
(ConstructorBindingImpl.java:111)
    at com.google.inject.FactoryProxy.get(FactoryProxy.java:56)
    at com.google.inject.InjectorImpl$4$1.call(InjectorImpl.java:758)
    at com.google.inject.InjectorImpl.callInContext
(InjectorImpl.java:811)
    at com.google.inject.InjectorImpl$4.get(InjectorImpl.java:754)
    at com.google.inject.multibindings.Multibinder$RealMultibinder.get
(Multibinder.java:266)
    at com.google.inject.multibindings.Multibinder$RealMultibinder.get
(Multibinder.java:194)
    at com.google.inject.InternalFactoryToProviderAdapter.get
(InternalFactoryToProviderAdapter.java:48)
    at com.google.inject.SingleParameterInjector.inject
(SingleParameterInjector.java:42)
    at com.google.inject.SingleParameterInjector.getAll
(SingleParameterInjector.java:66)
    at com.google.inject.ConstructorInjector.construct
(ConstructorInjector.java:84)
    at com.google.inject.ConstructorBindingImpl$Factory.get
(ConstructorBindingImpl.java:111)
    at com.google.inject.ProviderToInternalFactoryAdapter$1.call
(ProviderToInternalFactoryAdapter.java:45)
    at com.google.inject.InjectorImpl.callInContext
(InjectorImpl.java:811)
    at com.google.inject.ProviderToInternalFactoryAdapter.get
(ProviderToInternalFactoryAdapter.java:42)
    at com.google.injectScopes$1$1.get(Scopes.java:54)
    at com.google.inject.InternalFactoryToProviderAdapter.get
(InternalFactoryToProviderAdapter.java:48)
    at com.google.inject.InjectorImpl$3.get(InjectorImpl.java:549)
    at com.google.inject.BoundProviderFactory.get
(BoundProviderFactory.java:56)
    at com.google.inject.SingleParameterInjector.inject
(SingleParameterInjector.java:42)
    at com.google.inject.SingleParameterInjector.getAll
(SingleParameterInjector.java:66)
    at com.google.inject.ConstructorInjector.construct
(ConstructorInjector.java:84)
    at com.google.inject.ConstructorBindingImpl$Factory.get
(ConstructorBindingImpl.java:111)
    at com.google.inject.InjectorImpl$4$1.call(InjectorImpl.java:758)
    at com.google.inject.InjectorImpl.callInContext
(InjectorImpl.java:804)
    at com.google.inject.InjectorImpl$4.get(InjectorImpl.java:754)
    ... 2 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.inject.internal.ProviderMethod.get
(ProviderMethod.java:101)
    ... 32 more
Caused by: java.lang.RuntimeException: java.io.IOException: The system 
cannot find the path specified
    at 
com.google.jstestdriver.coverage.CoverageModule.createCoverageWriter
(Unknown Source)
    ... 37 more
Caused by: java.io.IOException: The system cannot find the path specified
    at java.io.WinNTFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:883)
    ... 38 more
------------------------------------------------------------------

What version of the product are you using? On what operating system?
Windows 2003, JsTestDriver 1.2, JsTestCoverage 1.2, MsBuild (for 
automating tasks).

Please provide any additional information below.
The whole process worked without the use of automation.

I have tried removing the source in the configuration file, and same error 
happened.  I am confident that the coverage.jar was found, but not sure 
what the above error means.

```

Original issue reported on code.google.com by `lighteni...@gmail.com` on 8 Jan 2010 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
It means that the test output path doesn't exist to write the coverage file.

Check your build environment to make sure the testOutput directory is going.
```

Original comment by `corbinrs...@gmail.com` on 10 Jan 2010 at 12:14

**Comment by GoogleCodeExporter** [comment]
```
I have tried many directories, e.g. the project's directory, c:\test etc. None 
of 
them worked.  The only directory that worked is the "." directory.  I tried 
appending sub directories to it, but the same error occurred.
```

Original comment by `lighteni...@gmail.com` on 10 Jan 2010 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
Update:

I entered ".", or the project's absolute directory (in Windows) for 
--testOutput.  
The error disappeared.  The test results were written in that directory.  
However, 
the coverage data turned out to be at the jscoverage.jar's location instead.

Is there a part of the JsTestCoverage's code that puts the coverage data in the 
coverage.jar's location instead of the testOutput dir if certain conditions are 
met?

```

Original comment by `lighteni...@gmail.com` on 12 Jan 2010 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
Oh. I see the error. It just uses the value of the testOutput, with resolving 
the
full path.
```

Original comment by `corbinrs...@gmail.com` on 18 Feb 2010 at 12:10
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Update:
still not working with JsTestDriver 1.2.1, coverage 1.2.1
```

Original comment by `nx1...@gmail.com` on 9 Apr 2010 at 8:11

**Comment by GoogleCodeExporter** [comment]
Original comment by `corbinrs...@gmail.com` on 28 Oct 2010 at 12:15
