### ISSUE TITLE
IDEA plugin doesn't work in RubyMine 2 or Idea 9

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#96]
```
What steps will reproduce the problem?
1. Install the plugin in RubyMine
2. Get exception

Forwarded conversation
Subject: JsTestDriver for RubyMine
------------------------

From: Misko Hevery <misko@hevery.com>
Date: Tue, Nov 3, 2009 at 9:49 AM
To: Adam Abrons <abrons@gmail.com>, Alex Eagle 
<alexeagle@google.com>


Hi Alex & Adam,

Alex is the author of the JsTestDriver for IDEA and Adam, is an eager user 
to have it working in his RubyMine. I figured that the two of you could chat 
to figure out why it is not working.

-- misko 

----------
From: Alex Eagle <alexeagle@google.com>
Date: Tue, Nov 3, 2009 at 12:09 PM
To: Misko Hevery <misko@hevery.com>
Cc: Adam Abrons <abrons@gmail.com>


Hey Adam,

I checked on the Jetbrains plugins repository, and it claims the plugin 
should be available on RubyMine - there's no separate place for me to 
upload it. My trial license for RubyMine expired, so it's not easy for me to 
test it myself.

Can you check if the plugin appears in the Plugin Manager list?

Thanks,
Alex

----------
From: Adam Abrons <abrons@gmail.com>
Date: Thu, Nov 5, 2009 at 1:32 PM
To: Alex Eagle <alexeagle@google.com>
Cc: Misko Hevery <misko@hevery.com>


Hi Alex, thanks for working on this.

JSTestDriver does appear in the RubyMine plugin manager, and can be 
installed, but there's an exception on loading it.  I ran the plugin 
successfully in the Maia/Idea 9.0 EAP build.  Here's the error I'm getting 
with RubyMine:
com/intellij/peer/PeerFactory: com/intellij/peer/PeerFactory
java.lang.NoClassDefFoundError: com/intellij/peer/PeerFactory
    at 
com.google.jstestdriver.idea.JSTestDriverToolWindow.initToolWindow(Unkn
own Source)
    at 
com.google.jstestdriver.idea.JSTestDriverToolWindow.projectOpened(Unkn
own Source)
    at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:85)
    at 
com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:1
15)
    at 
com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.pr
ojectOpened(ProjectImpl.java:7)
    at 
com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(Proj
ectManagerImpl.java:14)
    at 
com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl
.java:6)
    at 
com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectM
anagerImpl.java:106)
    at 
com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(Platform
ProjectOpenProcessor.java:41)
    at 
com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirec
toryProjectsManager.java:3)
    at 
com.intellij.ide.RecentProjectsManagerBase$ReopenProjectAction.actionPerf
ormed(RecentProjectsManagerBase.java:5)
    at 
com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFact
oryImpl.java:2)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:222)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:267)
    at 
com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:35)
    at 
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThrea
d.java:296)
    at 
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.ja
va:211)
    at 
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:201)
    at 
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at 
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: 
com.intellij.peer.PeerFactory
    at 
com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.ja
va:70)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:254)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:399)
    ... 23 more



java.lang.ClassNotFoundException: com.intellij.peer.PeerFactory
    at 
com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.ja
va:70)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:254)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:399)
    at 
com.google.jstestdriver.idea.JSTestDriverToolWindow.initToolWindow(Unkn
own Source)
    at 
com.google.jstestdriver.idea.JSTestDriverToolWindow.projectOpened(Unkn
own Source)
    at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:85)
    at 
com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:1
15)
    at 
com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.pr
ojectOpened(ProjectImpl.java:7)
    at 
com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(Proj
ectManagerImpl.java:14)
    at 
com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl
.java:6)
    at 
com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectM
anagerImpl.java:106)
    at 
com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(Platform
ProjectOpenProcessor.java:41)
    at 
com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirec
toryProjectsManager.java:3)
    at 
com.intellij.ide.RecentProjectsManagerBase$ReopenProjectAction.actionPerf
ormed(RecentProjectsManagerBase.java:5)
    at 
com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFact
oryImpl.java:2)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:222)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:267)
    at 
com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:35)
    at 
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThrea
d.java:296)
    at 
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.ja
va:211)
    at 
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:201)
    at 
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at 
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)


----------
From: Adam Abrons <abrons@gmail.com>
Date: Mon, Nov 30, 2009 at 9:55 AM
To: Alex Eagle <alexeagle@google.com>
Cc: Misko Hevery <misko@hevery.com>


hey Alex, have you had a chance to look at this?  Can I provide any more 
info?

-adam

----------
From: Alex Eagle <alexeagle@google.com>
Date: Mon, Dec 14, 2009 at 3:15 PM
To: Adam Abrons <abrons@gmail.com>, Cory Smith 
<corysmith@google.com>
Cc: Misko Hevery <misko@hevery.com>, Jeremie Lenfant-engelmann 
<jeremiele@google.com>


Finally trying to reproduce/fix this now. Here's my work log:

I ran RubyMine 2.0 and opened plugin manager, but was getting
List of plugins was not loaded: The markup in the document following
the root element must be well-formed.

Tried it one day last week and had the same problem. I found the issue
is that they changed the format of the plugins and fixed it in 2.0.1RC

Now the JSTestDriver plugin doesn't show up in the list of available
plugins. I built and manually copied to the plugins folder under
RubyMine, but it starts up with JSTestDriver disabled and a message
that it's incompatible.

Turns out there's a bug in RubyMine 2, which they haven't fixed yet,
which prevents it understanding the version numbering of plugins which
should be compatible.
http://www.jetbrains.net/devnet/message/5251836

Great... I removed the since-version from our plugin.xml as a
workaround, and was finally able to reproduce the exception you got.

I made a change in the code to avoid the PeerFactory class, which is
no longer available it seems. Of course, there's no documentation from
JetBrains, so the best alternative I found is a deprecated
constructor, but it's what some other plugins are doing.

Now the plugin window appears, but I can't execute a run
configuration. I suspect we need to build the plugin against the idea9
jars. We build against Java 5 to be nice to Mac people, but, that jar
is impossible to find anywhere on the various JetBrains sites.
Ignoring that problem and using the Java 6 class files that are
distributed with the IDE...

There are compile errors due to changes in the IDEA api's from version
8 to 9. I don't have time now to get a working IDE setup so I can fix
these...
Also, I think we'll need another branch if we want to continue to
maintain the plugin for IDEA 8.

Cory, what's the plan for supporting the idea plugin from this point?
I'm not sure when I'll get time to get this working with version 9 and
not sure where that is on the list of priorities, since we have some
users who still want to use version 7...
-Alex

----------
From: Cory Smith <corysmith@google.com>
Date: Tue, Dec 15, 2009 at 6:34 AM
To: Alex Eagle <alexeagle@google.com>
Cc: Adam Abrons <abrons@gmail.com>, Misko Hevery 
<misko@hevery.com>, Jeremie Lenfant-engelmann 
<jeremiele@google.com>


LCD.

I'm looking at baseline, no frills compatibility for the most widely used 
version.

Being set to 8 isn't great (I'd like 7 and 8, but Santa said something about a 
recession) but it will suit our needs for the .

I'm afraid RubyMine support is punted until someone really wants it 
enough to tangle with the issues you discovered. Switch the issue to a 
feature request and leave it open.

-c

```

Original issue reported on code.google.com by `alexea...@google.com` on 15 Jan 2010 at 6:36
- Merged into: #82

**Comment by GoogleCodeExporter** [comment]
```
Same error in PHPStorm 1.0.2 (same codebase, Maia).

I rebuid the plugin against new IDEA platform API and get it working but where 
is another kind of problem while trying to start JS-test-driver server through 
the IDE.

May be i need to share my fixes some way?


```

Original comment by `olegelif...@gmail.com` on 14 Sep 2010 at 4:45

**Comment by GoogleCodeExporter** [comment]
```
We've actually got some fixes on the way. See the latest commit on the project. 
We'll update this issue when we've got a release ready.
```

Original comment by `aeagle22206` on 14 Sep 2010 at 5:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `aeagle22206` on 14 Sep 2010 at 6:57
- Changed state: **Duplicate**
